// @generated from twemoji-assets
pub(super) const EMOJI_DATA: &[(&'static str, &'static str)] = &[
    ("🀄", "mahjong red dragon"),
    ("🃏", "joker"),
    ("🅰", "A button (blood type)"),
    ("🅱", "B button (blood type)"),
    ("🅾", "O button (blood type)"),
    ("🅿", "P button"),
    ("🆎", "AB button (blood type)"),
    ("🆑", "CL button"),
    ("🆒", "COOL button"),
    ("🆓", "FREE button"),
    ("🆔", "ID button"),
    ("🆕", "NEW button"),
    ("🆖", "NG button"),
    ("🆗", "OK button"),
    ("🆘", "SOS button"),
    ("🆙", "UP! button"),
    ("🆚", "VS button"),
    ("🇦🇨", "flag: Ascension Island"),
    ("🇦🇩", "flag: Andorra"),
    ("🇦🇪", "flag: United Arab Emirates"),
    ("🇦🇫", "flag: Afghanistan"),
    ("🇦🇬", "flag: Antigua & Barbuda"),
    ("🇦🇮", "flag: Anguilla"),
    ("🇦🇱", "flag: Albania"),
    ("🇦🇲", "flag: Armenia"),
    ("🇦🇴", "flag: Angola"),
    ("🇦🇶", "flag: Antarctica"),
    ("🇦🇷", "flag: Argentina"),
    ("🇦🇸", "flag: American Samoa"),
    ("🇦🇹", "flag: Austria"),
    ("🇦🇺", "flag: Australia"),
    ("🇦🇼", "flag: Aruba"),
    ("🇦🇽", "flag: Åland Islands"),
    ("🇦🇿", "flag: Azerbaijan"),
    ("🇦", "regional indicator A"),
    ("🇧🇦", "flag: Bosnia & Herzegovina"),
    ("🇧🇧", "flag: Barbados"),
    ("🇧🇩", "flag: Bangladesh"),
    ("🇧🇪", "flag: Belgium"),
    ("🇧🇫", "flag: Burkina Faso"),
    ("🇧🇬", "flag: Bulgaria"),
    ("🇧🇭", "flag: Bahrain"),
    ("🇧🇮", "flag: Burundi"),
    ("🇧🇯", "flag: Benin"),
    ("🇧🇱", "flag: St. Barthélemy"),
    ("🇧🇲", "flag: Bermuda"),
    ("🇧🇳", "flag: Brunei"),
    ("🇧🇴", "flag: Bolivia"),
    ("🇧🇶", "flag: Caribbean Netherlands"),
    ("🇧🇷", "flag: Brazil"),
    ("🇧🇸", "flag: Bahamas"),
    ("🇧🇹", "flag: Bhutan"),
    ("🇧🇻", "flag: Bouvet Island"),
    ("🇧🇼", "flag: Botswana"),
    ("🇧🇾", "flag: Belarus"),
    ("🇧🇿", "flag: Belize"),
    ("🇧", "regional indicator B"),
    ("🇨🇦", "flag: Canada"),
    ("🇨🇨", "flag: Cocos (Keeling) Islands"),
    ("🇨🇩", "flag: Congo - Kinshasa"),
    ("🇨🇫", "flag: Central African Republic"),
    ("🇨🇬", "flag: Congo - Brazzaville"),
    ("🇨🇭", "flag: Switzerland"),
    ("🇨🇮", "flag: Côte d’Ivoire"),
    ("🇨🇰", "flag: Cook Islands"),
    ("🇨🇱", "flag: Chile"),
    ("🇨🇲", "flag: Cameroon"),
    ("🇨🇳", "flag: China"),
    ("🇨🇴", "flag: Colombia"),
    ("🇨🇵", "flag: Clipperton Island"),
    ("🇨🇶", "flag: Sark"),
    ("🇨🇷", "flag: Costa Rica"),
    ("🇨🇺", "flag: Cuba"),
    ("🇨🇻", "flag: Cape Verde"),
    ("🇨🇼", "flag: Curaçao"),
    ("🇨🇽", "flag: Christmas Island"),
    ("🇨🇾", "flag: Cyprus"),
    ("🇨🇿", "flag: Czechia"),
    ("🇨", "regional indicator C"),
    ("🇩🇪", "flag: Germany"),
    ("🇩🇬", "flag: Diego Garcia"),
    ("🇩🇯", "flag: Djibouti"),
    ("🇩🇰", "flag: Denmark"),
    ("🇩🇲", "flag: Dominica"),
    ("🇩🇴", "flag: Dominican Republic"),
    ("🇩🇿", "flag: Algeria"),
    ("🇩", "regional indicator D"),
    ("🇪🇦", "flag: Ceuta & Melilla"),
    ("🇪🇨", "flag: Ecuador"),
    ("🇪🇪", "flag: Estonia"),
    ("🇪🇬", "flag: Egypt"),
    ("🇪🇭", "flag: Western Sahara"),
    ("🇪🇷", "flag: Eritrea"),
    ("🇪🇸", "flag: Spain"),
    ("🇪🇹", "flag: Ethiopia"),
    ("🇪🇺", "flag: European Union"),
    ("🇪", "regional indicator E"),
    ("🇫🇮", "flag: Finland"),
    ("🇫🇯", "flag: Fiji"),
    ("🇫🇰", "flag: Falkland Islands"),
    ("🇫🇲", "flag: Micronesia"),
    ("🇫🇴", "flag: Faroe Islands"),
    ("🇫🇷", "flag: France"),
    ("🇫", "regional indicator F"),
    ("🇬🇦", "flag: Gabon"),
    ("🇬🇧", "flag: United Kingdom"),
    ("🇬🇩", "flag: Grenada"),
    ("🇬🇪", "flag: Georgia"),
    ("🇬🇫", "flag: French Guiana"),
    ("🇬🇬", "flag: Guernsey"),
    ("🇬🇭", "flag: Ghana"),
    ("🇬🇮", "flag: Gibraltar"),
    ("🇬🇱", "flag: Greenland"),
    ("🇬🇲", "flag: Gambia"),
    ("🇬🇳", "flag: Guinea"),
    ("🇬🇵", "flag: Guadeloupe"),
    ("🇬🇶", "flag: Equatorial Guinea"),
    ("🇬🇷", "flag: Greece"),
    ("🇬🇸", "flag: South Georgia & South Sandwich Islands"),
    ("🇬🇹", "flag: Guatemala"),
    ("🇬🇺", "flag: Guam"),
    ("🇬🇼", "flag: Guinea-Bissau"),
    ("🇬🇾", "flag: Guyana"),
    ("🇬", "regional indicator G"),
    ("🇭🇰", "flag: Hong Kong SAR China"),
    ("🇭🇲", "flag: Heard & McDonald Islands"),
    ("🇭🇳", "flag: Honduras"),
    ("🇭🇷", "flag: Croatia"),
    ("🇭🇹", "flag: Haiti"),
    ("🇭🇺", "flag: Hungary"),
    ("🇭", "regional indicator H"),
    ("🇮🇨", "flag: Canary Islands"),
    ("🇮🇩", "flag: Indonesia"),
    ("🇮🇪", "flag: Ireland"),
    ("🇮🇱", "flag: Israel"),
    ("🇮🇲", "flag: Isle of Man"),
    ("🇮🇳", "flag: India"),
    ("🇮🇴", "flag: British Indian Ocean Territory"),
    ("🇮🇶", "flag: Iraq"),
    ("🇮🇷", "flag: Iran"),
    ("🇮🇸", "flag: Iceland"),
    ("🇮🇹", "flag: Italy"),
    ("🇮", "regional indicator I"),
    ("🇯🇪", "flag: Jersey"),
    ("🇯🇲", "flag: Jamaica"),
    ("🇯🇴", "flag: Jordan"),
    ("🇯🇵", "flag: Japan"),
    ("🇯", "regional indicator J"),
    ("🇰🇪", "flag: Kenya"),
    ("🇰🇬", "flag: Kyrgyzstan"),
    ("🇰🇭", "flag: Cambodia"),
    ("🇰🇮", "flag: Kiribati"),
    ("🇰🇲", "flag: Comoros"),
    ("🇰🇳", "flag: St. Kitts & Nevis"),
    ("🇰🇵", "flag: North Korea"),
    ("🇰🇷", "flag: South Korea"),
    ("🇰🇼", "flag: Kuwait"),
    ("🇰🇾", "flag: Cayman Islands"),
    ("🇰🇿", "flag: Kazakhstan"),
    ("🇰", "regional indicator K"),
    ("🇱🇦", "flag: Laos"),
    ("🇱🇧", "flag: Lebanon"),
    ("🇱🇨", "flag: St. Lucia"),
    ("🇱🇮", "flag: Liechtenstein"),
    ("🇱🇰", "flag: Sri Lanka"),
    ("🇱🇷", "flag: Liberia"),
    ("🇱🇸", "flag: Lesotho"),
    ("🇱🇹", "flag: Lithuania"),
    ("🇱🇺", "flag: Luxembourg"),
    ("🇱🇻", "flag: Latvia"),
    ("🇱🇾", "flag: Libya"),
    ("🇱", "regional indicator L"),
    ("🇲🇦", "flag: Morocco"),
    ("🇲🇨", "flag: Monaco"),
    ("🇲🇩", "flag: Moldova"),
    ("🇲🇪", "flag: Montenegro"),
    ("🇲🇫", "flag: St. Martin"),
    ("🇲🇬", "flag: Madagascar"),
    ("🇲🇭", "flag: Marshall Islands"),
    ("🇲🇰", "flag: North Macedonia"),
    ("🇲🇱", "flag: Mali"),
    ("🇲🇲", "flag: Myanmar (Burma)"),
    ("🇲🇳", "flag: Mongolia"),
    ("🇲🇴", "flag: Macao SAR China"),
    ("🇲🇵", "flag: Northern Mariana Islands"),
    ("🇲🇶", "flag: Martinique"),
    ("🇲🇷", "flag: Mauritania"),
    ("🇲🇸", "flag: Montserrat"),
    ("🇲🇹", "flag: Malta"),
    ("🇲🇺", "flag: Mauritius"),
    ("🇲🇻", "flag: Maldives"),
    ("🇲🇼", "flag: Malawi"),
    ("🇲🇽", "flag: Mexico"),
    ("🇲🇾", "flag: Malaysia"),
    ("🇲🇿", "flag: Mozambique"),
    ("🇲", "regional indicator M"),
    ("🇳🇦", "flag: Namibia"),
    ("🇳🇨", "flag: New Caledonia"),
    ("🇳🇪", "flag: Niger"),
    ("🇳🇫", "flag: Norfolk Island"),
    ("🇳🇬", "flag: Nigeria"),
    ("🇳🇮", "flag: Nicaragua"),
    ("🇳🇱", "flag: Netherlands"),
    ("🇳🇴", "flag: Norway"),
    ("🇳🇵", "flag: Nepal"),
    ("🇳🇷", "flag: Nauru"),
    ("🇳🇺", "flag: Niue"),
    ("🇳🇿", "flag: New Zealand"),
    ("🇳", "regional indicator N"),
    ("🇴🇲", "flag: Oman"),
    ("🇴", "regional indicator O"),
    ("🇵🇦", "flag: Panama"),
    ("🇵🇪", "flag: Peru"),
    ("🇵🇫", "flag: French Polynesia"),
    ("🇵🇬", "flag: Papua New Guinea"),
    ("🇵🇭", "flag: Philippines"),
    ("🇵🇰", "flag: Pakistan"),
    ("🇵🇱", "flag: Poland"),
    ("🇵🇲", "flag: St. Pierre & Miquelon"),
    ("🇵🇳", "flag: Pitcairn Islands"),
    ("🇵🇷", "flag: Puerto Rico"),
    ("🇵🇸", "flag: Palestinian Territories"),
    ("🇵🇹", "flag: Portugal"),
    ("🇵🇼", "flag: Palau"),
    ("🇵🇾", "flag: Paraguay"),
    ("🇵", "regional indicator P"),
    ("🇶🇦", "flag: Qatar"),
    ("🇶", "regional indicator Q"),
    ("🇷🇪", "flag: Réunion"),
    ("🇷🇴", "flag: Romania"),
    ("🇷🇸", "flag: Serbia"),
    ("🇷🇺", "flag: Russia"),
    ("🇷🇼", "flag: Rwanda"),
    ("🇷", "regional indicator R"),
    ("🇸🇦", "flag: Saudi Arabia"),
    ("🇸🇧", "flag: Solomon Islands"),
    ("🇸🇨", "flag: Seychelles"),
    ("🇸🇩", "flag: Sudan"),
    ("🇸🇪", "flag: Sweden"),
    ("🇸🇬", "flag: Singapore"),
    ("🇸🇭", "flag: St. Helena"),
    ("🇸🇮", "flag: Slovenia"),
    ("🇸🇯", "flag: Svalbard & Jan Mayen"),
    ("🇸🇰", "flag: Slovakia"),
    ("🇸🇱", "flag: Sierra Leone"),
    ("🇸🇲", "flag: San Marino"),
    ("🇸🇳", "flag: Senegal"),
    ("🇸🇴", "flag: Somalia"),
    ("🇸🇷", "flag: Suriname"),
    ("🇸🇸", "flag: South Sudan"),
    ("🇸🇹", "flag: São Tomé & Príncipe"),
    ("🇸🇻", "flag: El Salvador"),
    ("🇸🇽", "flag: Sint Maarten"),
    ("🇸🇾", "flag: Syria"),
    ("🇸🇿", "flag: Eswatini"),
    ("🇸", "regional indicator S"),
    ("🇹🇦", "flag: Tristan da Cunha"),
    ("🇹🇨", "flag: Turks & Caicos Islands"),
    ("🇹🇩", "flag: Chad"),
    ("🇹🇫", "flag: French Southern Territories"),
    ("🇹🇬", "flag: Togo"),
    ("🇹🇭", "flag: Thailand"),
    ("🇹🇯", "flag: Tajikistan"),
    ("🇹🇰", "flag: Tokelau"),
    ("🇹🇱", "flag: Timor-Leste"),
    ("🇹🇲", "flag: Turkmenistan"),
    ("🇹🇳", "flag: Tunisia"),
    ("🇹🇴", "flag: Tonga"),
    ("🇹🇷", "flag: Türkiye"),
    ("🇹🇹", "flag: Trinidad & Tobago"),
    ("🇹🇻", "flag: Tuvalu"),
    ("🇹🇼", "flag: Taiwan"),
    ("🇹🇿", "flag: Tanzania"),
    ("🇹", "regional indicator T"),
    ("🇺🇦", "flag: Ukraine"),
    ("🇺🇬", "flag: Uganda"),
    ("🇺🇲", "flag: U.S. Outlying Islands"),
    ("🇺🇳", "flag: United Nations"),
    ("🇺🇸", "flag: United States"),
    ("🇺🇾", "flag: Uruguay"),
    ("🇺🇿", "flag: Uzbekistan"),
    ("🇺", "regional indicator U"),
    ("🇻🇦", "flag: Vatican City"),
    ("🇻🇨", "flag: St. Vincent & Grenadines"),
    ("🇻🇪", "flag: Venezuela"),
    ("🇻🇬", "flag: British Virgin Islands"),
    ("🇻🇮", "flag: U.S. Virgin Islands"),
    ("🇻🇳", "flag: Vietnam"),
    ("🇻🇺", "flag: Vanuatu"),
    ("🇻", "regional indicator V"),
    ("🇼🇫", "flag: Wallis & Futuna"),
    ("🇼🇸", "flag: Samoa"),
    ("🇼", "regional indicator W"),
    ("🇽🇰", "flag: Kosovo"),
    ("🇽", "regional indicator X"),
    ("🇾🇪", "flag: Yemen"),
    ("🇾🇹", "flag: Mayotte"),
    ("🇾", "regional indicator Y"),
    ("🇿🇦", "flag: South Africa"),
    ("🇿🇲", "flag: Zambia"),
    ("🇿🇼", "flag: Zimbabwe"),
    ("🇿", "regional indicator Z"),
    ("🈁", "Japanese “here” button"),
    ("🈂", "Japanese “service charge” button"),
    ("🈚", "Japanese “free of charge” button"),
    ("🈯", "Japanese “reserved” button"),
    ("🈲", "Japanese “prohibited” button"),
    ("🈳", "Japanese “vacancy” button"),
    ("🈴", "Japanese “passing grade” button"),
    ("🈵", "Japanese “no vacancy” button"),
    ("🈶", "Japanese “not free of charge” button"),
    ("🈷", "Japanese “monthly amount” button"),
    ("🈸", "Japanese “application” button"),
    ("🈹", "Japanese “discount” button"),
    ("🈺", "Japanese “open for business” button"),
    ("🉐", "Japanese “bargain” button"),
    ("🉑", "Japanese “acceptable” button"),
    ("🌀", "cyclone"),
    ("🌁", "foggy"),
    ("🌂", "closed umbrella"),
    ("🌃", "night with stars"),
    ("🌄", "sunrise over mountains"),
    ("🌅", "sunrise"),
    ("🌆", "cityscape at dusk"),
    ("🌇", "sunset"),
    ("🌈", "rainbow"),
    ("🌉", "bridge at night"),
    ("🌊", "water wave"),
    ("🌋", "volcano"),
    ("🌌", "milky way"),
    ("🌍", "globe showing Europe-Africa"),
    ("🌎", "globe showing Americas"),
    ("🌏", "globe showing Asia-Australia"),
    ("🌐", "globe with meridians"),
    ("🌑", "new moon"),
    ("🌒", "waxing crescent moon"),
    ("🌓", "first quarter moon"),
    ("🌔", "waxing gibbous moon"),
    ("🌕", "full moon"),
    ("🌖", "waning gibbous moon"),
    ("🌗", "last quarter moon"),
    ("🌘", "waning crescent moon"),
    ("🌙", "crescent moon"),
    ("🌚", "new moon face"),
    ("🌛", "first quarter moon face"),
    ("🌜", "last quarter moon face"),
    ("🌝", "full moon face"),
    ("🌞", "sun with face"),
    ("🌟", "glowing star"),
    ("🌠", "shooting star"),
    ("🌡", "thermometer"),
    ("🌤", "sun behind small cloud"),
    ("🌥", "sun behind large cloud"),
    ("🌦", "sun behind rain cloud"),
    ("🌧", "cloud with rain"),
    ("🌨", "cloud with snow"),
    ("🌩", "cloud with lightning"),
    ("🌪", "tornado"),
    ("🌫", "fog"),
    ("🌬", "wind face"),
    ("🌭", "hot dog"),
    ("🌮", "taco"),
    ("🌯", "burrito"),
    ("🌰", "chestnut"),
    ("🌱", "seedling"),
    ("🌲", "evergreen tree"),
    ("🌳", "deciduous tree"),
    ("🌴", "palm tree"),
    ("🌵", "cactus"),
    ("🌶", "hot pepper"),
    ("🌷", "tulip"),
    ("🌸", "cherry blossom"),
    ("🌹", "rose"),
    ("🌺", "hibiscus"),
    ("🌻", "sunflower"),
    ("🌼", "blossom"),
    ("🌽", "ear of corn"),
    ("🌾", "sheaf of rice"),
    ("🌿", "herb"),
    ("🍀", "four leaf clover"),
    ("🍁", "maple leaf"),
    ("🍂", "fallen leaf"),
    ("🍃", "leaf fluttering in wind"),
    ("🍄‍🟫", "brown mushroom"),
    ("🍄", "mushroom"),
    ("🍅", "tomato"),
    ("🍆", "eggplant"),
    ("🍇", "grapes"),
    ("🍈", "melon"),
    ("🍉", "watermelon"),
    ("🍊", "tangerine"),
    ("🍋‍🟩", "lime"),
    ("🍋", "lemon"),
    ("🍌", "banana"),
    ("🍍", "pineapple"),
    ("🍎", "red apple"),
    ("🍏", "green apple"),
    ("🍐", "pear"),
    ("🍑", "peach"),
    ("🍒", "cherries"),
    ("🍓", "strawberry"),
    ("🍔", "hamburger"),
    ("🍕", "pizza"),
    ("🍖", "meat on bone"),
    ("🍗", "poultry leg"),
    ("🍘", "rice cracker"),
    ("🍙", "rice ball"),
    ("🍚", "cooked rice"),
    ("🍛", "curry rice"),
    ("🍜", "steaming bowl"),
    ("🍝", "spaghetti"),
    ("🍞", "bread"),
    ("🍟", "french fries"),
    ("🍠", "roasted sweet potato"),
    ("🍡", "dango"),
    ("🍢", "oden"),
    ("🍣", "sushi"),
    ("🍤", "fried shrimp"),
    ("🍥", "fish cake with swirl"),
    ("🍦", "soft ice cream"),
    ("🍧", "shaved ice"),
    ("🍨", "ice cream"),
    ("🍩", "doughnut"),
    ("🍪", "cookie"),
    ("🍫", "chocolate bar"),
    ("🍬", "candy"),
    ("🍭", "lollipop"),
    ("🍮", "custard"),
    ("🍯", "honey pot"),
    ("🍰", "shortcake"),
    ("🍱", "bento box"),
    ("🍲", "pot of food"),
    ("🍳", "cooking"),
    ("🍴", "fork and knife"),
    ("🍵", "teacup without handle"),
    ("🍶", "sake"),
    ("🍷", "wine glass"),
    ("🍸", "cocktail glass"),
    ("🍹", "tropical drink"),
    ("🍺", "beer mug"),
    ("🍻", "clinking beer mugs"),
    ("🍼", "baby bottle"),
    ("🍽", "fork and knife with plate"),
    ("🍾", "bottle with popping cork"),
    ("🍿", "popcorn"),
    ("🎀", "ribbon"),
    ("🎁", "wrapped gift"),
    ("🎂", "birthday cake"),
    ("🎃", "jack-o-lantern"),
    ("🎄", "Christmas tree"),
    ("🎅", "Santa Claus"),
    ("🎆", "fireworks"),
    ("🎇", "sparkler"),
    ("🎈", "balloon"),
    ("🎉", "party popper"),
    ("🎊", "confetti ball"),
    ("🎋", "tanabata tree"),
    ("🎌", "crossed flags"),
    ("🎍", "pine decoration"),
    ("🎎", "Japanese dolls"),
    ("🎏", "carp streamer"),
    ("🎐", "wind chime"),
    ("🎑", "moon viewing ceremony"),
    ("🎒", "backpack"),
    ("🎓", "graduation cap"),
    ("🎖", "military medal"),
    ("🎗", "reminder ribbon"),
    ("🎙", "studio microphone"),
    ("🎚", "level slider"),
    ("🎛", "control knobs"),
    ("🎞", "film frames"),
    ("🎟", "admission tickets"),
    ("🎠", "carousel horse"),
    ("🎡", "ferris wheel"),
    ("🎢", "roller coaster"),
    ("🎣", "fishing pole"),
    ("🎤", "microphone"),
    ("🎥", "movie camera"),
    ("🎦", "cinema"),
    ("🎧", "headphone"),
    ("🎨", "artist palette"),
    ("🎩", "top hat"),
    ("🎪", "circus tent"),
    ("🎫", "ticket"),
    ("🎬", "clapper board"),
    ("🎭", "performing arts"),
    ("🎮", "video game"),
    ("🎯", "bullseye"),
    ("🎰", "slot machine"),
    ("🎱", "pool 8 ball"),
    ("🎲", "game die"),
    ("🎳", "bowling"),
    ("🎴", "flower playing cards"),
    ("🎵", "musical note"),
    ("🎶", "musical notes"),
    ("🎷", "saxophone"),
    ("🎸", "guitar"),
    ("🎹", "musical keyboard"),
    ("🎺", "trumpet"),
    ("🎻", "violin"),
    ("🎼", "musical score"),
    ("🎽", "running shirt"),
    ("🎾", "tennis"),
    ("🎿", "skis"),
    ("🏀", "basketball"),
    ("🏁", "chequered flag"),
    ("🏂", "snowboarder"),
    ("🏃‍♀️‍➡️", "woman running facing right"),
    ("🏃‍♀️", "woman running"),
    ("🏃‍♂️‍➡️", "man running facing right"),
    ("🏃‍♂️", "man running"),
    ("🏃‍➡️", "person running facing right"),
    ("🏃", "person running"),
    ("🏄‍♀️", "woman surfing"),
    ("🏄‍♂️", "man surfing"),
    ("🏄", "person surfing"),
    ("🏅", "sports medal"),
    ("🏆", "trophy"),
    ("🏇", "horse racing"),
    ("🏈", "american football"),
    ("🏉", "rugby football"),
    ("🏊‍♀️", "woman swimming"),
    ("🏊‍♂️", "man swimming"),
    ("🏊", "person swimming"),
    ("🏋️‍♀️", "woman lifting weights"),
    ("🏋️‍♂️", "man lifting weights"),
    ("🏋", "person lifting weights"),
    ("🏌️‍♀️", "woman golfing"),
    ("🏌️‍♂️", "man golfing"),
    ("🏌", "person golfing"),
    ("🏍", "motorcycle"),
    ("🏎", "racing car"),
    ("🏏", "cricket game"),
    ("🏐", "volleyball"),
    ("🏑", "field hockey"),
    ("🏒", "ice hockey"),
    ("🏓", "ping pong"),
    ("🏔", "snow-capped mountain"),
    ("🏕", "camping"),
    ("🏖", "beach with umbrella"),
    ("🏗", "building construction"),
    ("🏘", "houses"),
    ("🏙", "cityscape"),
    ("🏚", "derelict house"),
    ("🏛", "classical building"),
    ("🏜", "desert"),
    ("🏝", "desert island"),
    ("🏞", "national park"),
    ("🏟", "stadium"),
    ("🏠", "house"),
    ("🏡", "house with garden"),
    ("🏢", "office building"),
    ("🏣", "Japanese post office"),
    ("🏤", "post office"),
    ("🏥", "hospital"),
    ("🏦", "bank"),
    ("🏧", "ATM sign"),
    ("🏨", "hotel"),
    ("🏩", "love hotel"),
    ("🏪", "convenience store"),
    ("🏫", "school"),
    ("🏬", "department store"),
    ("🏭", "factory"),
    ("🏮", "red paper lantern"),
    ("🏯", "Japanese castle"),
    ("🏰", "castle"),
    ("🏳️‍🌈", "rainbow flag"),
    ("🏳️‍⚧️", "transgender flag"),
    ("🏳", "white flag"),
    ("🏴‍☠️", "pirate flag"),
    ("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "flag: England"),
    ("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "flag: Scotland"),
    ("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "flag: Wales"),
    ("🏴", "black flag"),
    ("🏵", "rosette"),
    ("🏷", "label"),
    ("🏸", "badminton"),
    ("🏹", "bow and arrow"),
    ("🏺", "amphora"),
    ("🏻", "light skin tone"),
    ("🏼", "medium-light skin tone"),
    ("🏽", "medium skin tone"),
    ("🏾", "medium-dark skin tone"),
    ("🏿", "dark skin tone"),
    ("🐀", "rat"),
    ("🐁", "mouse"),
    ("🐂", "ox"),
    ("🐃", "water buffalo"),
    ("🐄", "cow"),
    ("🐅", "tiger"),
    ("🐆", "leopard"),
    ("🐇", "rabbit"),
    ("🐈‍⬛", "black cat"),
    ("🐈", "cat"),
    ("🐉", "dragon"),
    ("🐊", "crocodile"),
    ("🐋", "whale"),
    ("🐌", "snail"),
    ("🐍", "snake"),
    ("🐎", "horse"),
    ("🐏", "ram"),
    ("🐐", "goat"),
    ("🐑", "ewe"),
    ("🐒", "monkey"),
    ("🐓", "rooster"),
    ("🐔", "chicken"),
    ("🐕‍🦺", "service dog"),
    ("🐕", "dog"),
    ("🐖", "pig"),
    ("🐗", "boar"),
    ("🐘", "elephant"),
    ("🐙", "octopus"),
    ("🐚", "spiral shell"),
    ("🐛", "bug"),
    ("🐜", "ant"),
    ("🐝", "honeybee"),
    ("🐞", "lady beetle"),
    ("🐟", "fish"),
    ("🐠", "tropical fish"),
    ("🐡", "blowfish"),
    ("🐢", "turtle"),
    ("🐣", "hatching chick"),
    ("🐤", "baby chick"),
    ("🐥", "front-facing baby chick"),
    ("🐦‍🔥", "phoenix"),
    ("🐦‍⬛", "black bird"),
    ("🐦", "bird"),
    ("🐧", "penguin"),
    ("🐨", "koala"),
    ("🐩", "poodle"),
    ("🐪", "camel"),
    ("🐫", "two-hump camel"),
    ("🐬", "dolphin"),
    ("🐭", "mouse face"),
    ("🐮", "cow face"),
    ("🐯", "tiger face"),
    ("🐰", "rabbit face"),
    ("🐱", "cat face"),
    ("🐲", "dragon face"),
    ("🐳", "spouting whale"),
    ("🐴", "horse face"),
    ("🐵", "monkey face"),
    ("🐶", "dog face"),
    ("🐷", "pig face"),
    ("🐸", "frog"),
    ("🐹", "hamster"),
    ("🐺", "wolf"),
    ("🐻‍❄️", "polar bear"),
    ("🐻", "bear"),
    ("🐼", "panda"),
    ("🐽", "pig nose"),
    ("🐾", "paw prints"),
    ("🐿", "chipmunk"),
    ("👀", "eyes"),
    ("👁", "eye"),
    ("👂", "ear"),
    ("👃", "nose"),
    ("👄", "mouth"),
    ("👅", "tongue"),
    ("👆", "backhand index pointing up"),
    ("👇", "backhand index pointing down"),
    ("👈", "backhand index pointing left"),
    ("👉", "backhand index pointing right"),
    ("👊", "oncoming fist"),
    ("👋", "waving hand"),
    ("👌", "OK hand"),
    ("👍", "thumbs up"),
    ("👎", "thumbs down"),
    ("👏", "clapping hands"),
    ("👐", "open hands"),
    ("👑", "crown"),
    ("👒", "woman’s hat"),
    ("👓", "glasses"),
    ("👔", "necktie"),
    ("👕", "t-shirt"),
    ("👖", "jeans"),
    ("👗", "dress"),
    ("👘", "kimono"),
    ("👙", "bikini"),
    ("👚", "woman’s clothes"),
    ("👛", "purse"),
    ("👜", "handbag"),
    ("👝", "clutch bag"),
    ("👞", "man’s shoe"),
    ("👟", "running shoe"),
    ("👠", "high-heeled shoe"),
    ("👡", "woman’s sandal"),
    ("👢", "woman’s boot"),
    ("👣", "footprints"),
    ("👤", "bust in silhouette"),
    ("👥", "busts in silhouette"),
    ("👦", "boy"),
    ("👧", "girl"),
    ("👨‍🌾", "man farmer"),
    ("👨‍🍳", "man cook"),
    ("👨‍🍼", "man feeding baby"),
    ("👨‍🎓", "man student"),
    ("👨‍🎤", "man singer"),
    ("👨‍🎨", "man artist"),
    ("👨‍🏫", "man teacher"),
    ("👨‍🏭", "man factory worker"),
    ("👨‍👦‍👦", "family: man, boy, boy"),
    ("👨‍👦", "family: man, boy"),
    ("👨‍👧‍👦", "family: man, girl, boy"),
    ("👨‍👧‍👧", "family: man, girl, girl"),
    ("👨‍👧", "family: man, girl"),
    ("👨‍👨‍👦‍👦", "family: man, man, boy, boy"),
    ("👨‍👨‍👦", "family: man, man, boy"),
    ("👨‍👨‍👧‍👦", "family: man, man, girl, boy"),
    ("👨‍👨‍👧‍👧", "family: man, man, girl, girl"),
    ("👨‍👨‍👧", "family: man, man, girl"),
    ("👨‍👩‍👦‍👦", "family: man, woman, boy, boy"),
    ("👨‍👩‍👦", "family: man, woman, boy"),
    ("👨‍👩‍👧‍👦", "family: man, woman, girl, boy"),
    ("👨‍👩‍👧‍👧", "family: man, woman, girl, girl"),
    ("👨‍👩‍👧", "family: man, woman, girl"),
    ("👨‍💻", "man technologist"),
    ("👨‍💼", "man office worker"),
    ("👨‍🔧", "man mechanic"),
    ("👨‍🔬", "man scientist"),
    ("👨‍🚀", "man astronaut"),
    ("👨‍🚒", "man firefighter"),
    ("👨‍🦯‍➡️", "man with white cane facing right"),
    ("👨‍🦯", "man with white cane"),
    ("👨‍🦰", "man: red hair"),
    ("👨‍🦱", "man: curly hair"),
    ("👨‍🦲", "man: bald"),
    ("👨‍🦳", "man: white hair"),
    ("👨‍🦼‍➡️", "man in motorized wheelchair facing right"),
    ("👨‍🦼", "man in motorized wheelchair"),
    ("👨‍🦽‍➡️", "man in manual wheelchair facing right"),
    ("👨‍🦽", "man in manual wheelchair"),
    ("👨‍⚕️", "man health worker"),
    ("👨‍⚖️", "man judge"),
    ("👨‍✈️", "man pilot"),
    ("👨‍❤️‍👨", "couple with heart: man, man"),
    ("👨‍❤️‍💋‍👨", "kiss: man, man"),
    ("👨", "man"),
    ("👩‍🌾", "woman farmer"),
    ("👩‍🍳", "woman cook"),
    ("👩‍🍼", "woman feeding baby"),
    ("👩‍🎓", "woman student"),
    ("👩‍🎤", "woman singer"),
    ("👩‍🎨", "woman artist"),
    ("👩‍🏫", "woman teacher"),
    ("👩‍🏭", "woman factory worker"),
    ("👩‍👦‍👦", "family: woman, boy, boy"),
    ("👩‍👦", "family: woman, boy"),
    ("👩‍👧‍👦", "family: woman, girl, boy"),
    ("👩‍👧‍👧", "family: woman, girl, girl"),
    ("👩‍👧", "family: woman, girl"),
    ("👩‍👩‍👦‍👦", "family: woman, woman, boy, boy"),
    ("👩‍👩‍👦", "family: woman, woman, boy"),
    ("👩‍👩‍👧‍👦", "family: woman, woman, girl, boy"),
    ("👩‍👩‍👧‍👧", "family: woman, woman, girl, girl"),
    ("👩‍👩‍👧", "family: woman, woman, girl"),
    ("👩‍💻", "woman technologist"),
    ("👩‍💼", "woman office worker"),
    ("👩‍🔧", "woman mechanic"),
    ("👩‍🔬", "woman scientist"),
    ("👩‍🚀", "woman astronaut"),
    ("👩‍🚒", "woman firefighter"),
    ("👩‍🦯‍➡️", "woman with white cane facing right"),
    ("👩‍🦯", "woman with white cane"),
    ("👩‍🦰", "woman: red hair"),
    ("👩‍🦱", "woman: curly hair"),
    ("👩‍🦲", "woman: bald"),
    ("👩‍🦳", "woman: white hair"),
    ("👩‍🦼‍➡️", "woman in motorized wheelchair facing right"),
    ("👩‍🦼", "woman in motorized wheelchair"),
    ("👩‍🦽‍➡️", "woman in manual wheelchair facing right"),
    ("👩‍🦽", "woman in manual wheelchair"),
    ("👩‍⚕️", "woman health worker"),
    ("👩‍⚖️", "woman judge"),
    ("👩‍✈️", "woman pilot"),
    ("👩‍❤️‍👨", "couple with heart: woman, man"),
    ("👩‍❤️‍👩", "couple with heart: woman, woman"),
    ("👩‍❤️‍💋‍👨", "kiss: woman, man"),
    ("👩‍❤️‍💋‍👩", "kiss: woman, woman"),
    ("👩", "woman"),
    ("👪", "family"),
    ("👫", "woman and man holding hands"),
    ("👬", "men holding hands"),
    ("👭", "women holding hands"),
    ("👮‍♀️", "woman police officer"),
    ("👮‍♂️", "man police officer"),
    ("👮", "police officer"),
    ("👯‍♀️", "women with bunny ears"),
    ("👯‍♂️", "men with bunny ears"),
    ("👯", "people with bunny ears"),
    ("👰‍♀️", "woman with veil"),
    ("👰‍♂️", "man with veil"),
    ("👰", "person with veil"),
    ("👱‍♀️", "woman: blond hair"),
    ("👱‍♂️", "man: blond hair"),
    ("👱", "person: blond hair"),
    ("👲", "person with skullcap"),
    ("👳‍♀️", "woman wearing turban"),
    ("👳‍♂️", "man wearing turban"),
    ("👳", "person wearing turban"),
    ("👴", "old man"),
    ("👵", "old woman"),
    ("👶", "baby"),
    ("👷‍♀️", "woman construction worker"),
    ("👷‍♂️", "man construction worker"),
    ("👷", "construction worker"),
    ("👸", "princess"),
    ("👹", "ogre"),
    ("👺", "goblin"),
    ("👻", "ghost"),
    ("👼", "baby angel"),
    ("👽", "alien"),
    ("👾", "alien monster"),
    ("👿", "angry face with horns"),
    ("💀", "skull"),
    ("💁‍♀️", "woman tipping hand"),
    ("💁‍♂️", "man tipping hand"),
    ("💁", "person tipping hand"),
    ("💂‍♀️", "woman guard"),
    ("💂‍♂️", "man guard"),
    ("💂", "guard"),
    ("💃", "woman dancing"),
    ("💄", "lipstick"),
    ("💅", "nail polish"),
    ("💆‍♀️", "woman getting massage"),
    ("💆‍♂️", "man getting massage"),
    ("💆", "person getting massage"),
    ("💇‍♀️", "woman getting haircut"),
    ("💇‍♂️", "man getting haircut"),
    ("💇", "person getting haircut"),
    ("💈", "barber pole"),
    ("💉", "syringe"),
    ("💊", "pill"),
    ("💋", "kiss mark"),
    ("💌", "love letter"),
    ("💍", "ring"),
    ("💎", "gem stone"),
    ("💏", "kiss"),
    ("💐", "bouquet"),
    ("💑", "couple with heart"),
    ("💒", "wedding"),
    ("💓", "beating heart"),
    ("💔", "broken heart"),
    ("💕", "two hearts"),
    ("💖", "sparkling heart"),
    ("💗", "growing heart"),
    ("💘", "heart with arrow"),
    ("💙", "blue heart"),
    ("💚", "green heart"),
    ("💛", "yellow heart"),
    ("💜", "purple heart"),
    ("💝", "heart with ribbon"),
    ("💞", "revolving hearts"),
    ("💟", "heart decoration"),
    ("💠", "diamond with a dot"),
    ("💡", "light bulb"),
    ("💢", "anger symbol"),
    ("💣", "bomb"),
    ("💤", "ZZZ"),
    ("💥", "collision"),
    ("💦", "sweat droplets"),
    ("💧", "droplet"),
    ("💨", "dashing away"),
    ("💩", "pile of poo"),
    ("💪", "flexed biceps"),
    ("💫", "dizzy"),
    ("💬", "speech balloon"),
    ("💭", "thought balloon"),
    ("💮", "white flower"),
    ("💯", "hundred points"),
    ("💰", "money bag"),
    ("💱", "currency exchange"),
    ("💲", "heavy dollar sign"),
    ("💳", "credit card"),
    ("💴", "yen banknote"),
    ("💵", "dollar banknote"),
    ("💶", "euro banknote"),
    ("💷", "pound banknote"),
    ("💸", "money with wings"),
    ("💹", "chart increasing with yen"),
    ("💺", "seat"),
    ("💻", "laptop"),
    ("💼", "briefcase"),
    ("💽", "computer disk"),
    ("💾", "floppy disk"),
    ("💿", "optical disk"),
    ("📀", "dvd"),
    ("📁", "file folder"),
    ("📂", "open file folder"),
    ("📃", "page with curl"),
    ("📄", "page facing up"),
    ("📅", "calendar"),
    ("📆", "tear-off calendar"),
    ("📇", "card index"),
    ("📈", "chart increasing"),
    ("📉", "chart decreasing"),
    ("📊", "bar chart"),
    ("📋", "clipboard"),
    ("📌", "pushpin"),
    ("📍", "round pushpin"),
    ("📎", "paperclip"),
    ("📏", "straight ruler"),
    ("📐", "triangular ruler"),
    ("📑", "bookmark tabs"),
    ("📒", "ledger"),
    ("📓", "notebook"),
    ("📔", "notebook with decorative cover"),
    ("📕", "closed book"),
    ("📖", "open book"),
    ("📗", "green book"),
    ("📘", "blue book"),
    ("📙", "orange book"),
    ("📚", "books"),
    ("📛", "name badge"),
    ("📜", "scroll"),
    ("📝", "memo"),
    ("📞", "telephone receiver"),
    ("📟", "pager"),
    ("📠", "fax machine"),
    ("📡", "satellite antenna"),
    ("📢", "loudspeaker"),
    ("📣", "megaphone"),
    ("📤", "outbox tray"),
    ("📥", "inbox tray"),
    ("📦", "package"),
    ("📧", "e-mail"),
    ("📨", "incoming envelope"),
    ("📩", "envelope with arrow"),
    ("📪", "closed mailbox with lowered flag"),
    ("📫", "closed mailbox with raised flag"),
    ("📬", "open mailbox with raised flag"),
    ("📭", "open mailbox with lowered flag"),
    ("📮", "postbox"),
    ("📯", "postal horn"),
    ("📰", "newspaper"),
    ("📱", "mobile phone"),
    ("📲", "mobile phone with arrow"),
    ("📳", "vibration mode"),
    ("📴", "mobile phone off"),
    ("📵", "no mobile phones"),
    ("📶", "antenna bars"),
    ("📷", "camera"),
    ("📸", "camera with flash"),
    ("📹", "video camera"),
    ("📺", "television"),
    ("📻", "radio"),
    ("📼", "videocassette"),
    ("📽", "film projector"),
    ("📿", "prayer beads"),
    ("🔀", "shuffle tracks button"),
    ("🔁", "repeat button"),
    ("🔂", "repeat single button"),
    ("🔃", "clockwise vertical arrows"),
    ("🔄", "counterclockwise arrows button"),
    ("🔅", "dim button"),
    ("🔆", "bright button"),
    ("🔇", "muted speaker"),
    ("🔈", "speaker low volume"),
    ("🔉", "speaker medium volume"),
    ("🔊", "speaker high volume"),
    ("🔋", "battery"),
    ("🔌", "electric plug"),
    ("🔍", "magnifying glass tilted left"),
    ("🔎", "magnifying glass tilted right"),
    ("🔏", "locked with pen"),
    ("🔐", "locked with key"),
    ("🔑", "key"),
    ("🔒", "locked"),
    ("🔓", "unlocked"),
    ("🔔", "bell"),
    ("🔕", "bell with slash"),
    ("🔖", "bookmark"),
    ("🔗", "link"),
    ("🔘", "radio button"),
    ("🔙", "BACK arrow"),
    ("🔚", "END arrow"),
    ("🔛", "ON! arrow"),
    ("🔜", "SOON arrow"),
    ("🔝", "TOP arrow"),
    ("🔞", "no one under eighteen"),
    ("🔟", "keycap: 10"),
    ("🔠", "input latin uppercase"),
    ("🔡", "input latin lowercase"),
    ("🔢", "input numbers"),
    ("🔣", "input symbols"),
    ("🔤", "input latin letters"),
    ("🔥", "fire"),
    ("🔦", "flashlight"),
    ("🔧", "wrench"),
    ("🔨", "hammer"),
    ("🔩", "nut and bolt"),
    ("🔪", "kitchen knife"),
    ("🔫", "water pistol"),
    ("🔬", "microscope"),
    ("🔭", "telescope"),
    ("🔮", "crystal ball"),
    ("🔯", "dotted six-pointed star"),
    ("🔰", "Japanese symbol for beginner"),
    ("🔱", "trident emblem"),
    ("🔲", "black square button"),
    ("🔳", "white square button"),
    ("🔴", "red circle"),
    ("🔵", "blue circle"),
    ("🔶", "large orange diamond"),
    ("🔷", "large blue diamond"),
    ("🔸", "small orange diamond"),
    ("🔹", "small blue diamond"),
    ("🔺", "red triangle pointed up"),
    ("🔻", "red triangle pointed down"),
    ("🔼", "upwards button"),
    ("🔽", "downwards button"),
    ("🕉", "om"),
    ("🕊", "dove"),
    ("🕋", "kaaba"),
    ("🕌", "mosque"),
    ("🕍", "synagogue"),
    ("🕎", "menorah"),
    ("🕐", "one o’clock"),
    ("🕑", "two o’clock"),
    ("🕒", "three o’clock"),
    ("🕓", "four o’clock"),
    ("🕔", "five o’clock"),
    ("🕕", "six o’clock"),
    ("🕖", "seven o’clock"),
    ("🕗", "eight o’clock"),
    ("🕘", "nine o’clock"),
    ("🕙", "ten o’clock"),
    ("🕚", "eleven o’clock"),
    ("🕛", "twelve o’clock"),
    ("🕜", "one-thirty"),
    ("🕝", "two-thirty"),
    ("🕞", "three-thirty"),
    ("🕟", "four-thirty"),
    ("🕠", "five-thirty"),
    ("🕡", "six-thirty"),
    ("🕢", "seven-thirty"),
    ("🕣", "eight-thirty"),
    ("🕤", "nine-thirty"),
    ("🕥", "ten-thirty"),
    ("🕦", "eleven-thirty"),
    ("🕧", "twelve-thirty"),
    ("🕯", "candle"),
    ("🕰", "mantelpiece clock"),
    ("🕳", "hole"),
    ("🕴", "person in suit levitating"),
    ("🕵️‍♀️", "woman detective"),
    ("🕵️‍♂️", "man detective"),
    ("🕵", "detective"),
    ("🕶", "sunglasses"),
    ("🕷", "spider"),
    ("🕸", "spider web"),
    ("🕹", "joystick"),
    ("🕺", "man dancing"),
    ("🖇", "linked paperclips"),
    ("🖊", "pen"),
    ("🖋", "fountain pen"),
    ("🖌", "paintbrush"),
    ("🖍", "crayon"),
    ("🖐", "hand with fingers splayed"),
    ("🖕", "middle finger"),
    ("🖖", "vulcan salute"),
    ("🖤", "black heart"),
    ("🖥", "desktop computer"),
    ("🖨", "printer"),
    ("🖱", "computer mouse"),
    ("🖲", "trackball"),
    ("🖼", "framed picture"),
    ("🗂", "card index dividers"),
    ("🗃", "card file box"),
    ("🗄", "file cabinet"),
    ("🗑", "wastebasket"),
    ("🗒", "spiral notepad"),
    ("🗓", "spiral calendar"),
    ("🗜", "clamp"),
    ("🗝", "old key"),
    ("🗞", "rolled-up newspaper"),
    ("🗡", "dagger"),
    ("🗣", "speaking head"),
    ("🗨", "left speech bubble"),
    ("🗯", "right anger bubble"),
    ("🗳", "ballot box with ballot"),
    ("🗺", "world map"),
    ("🗻", "mount fuji"),
    ("🗼", "Tokyo tower"),
    ("🗽", "Statue of Liberty"),
    ("🗾", "map of Japan"),
    ("🗿", "moai"),
    ("😀", "grinning face"),
    ("😁", "beaming face with smiling eyes"),
    ("😂", "face with tears of joy"),
    ("😃", "grinning face with big eyes"),
    ("😄", "grinning face with smiling eyes"),
    ("😅", "grinning face with sweat"),
    ("😆", "grinning squinting face"),
    ("😇", "smiling face with halo"),
    ("😈", "smiling face with horns"),
    ("😉", "winking face"),
    ("😊", "smiling face with smiling eyes"),
    ("😋", "face savoring food"),
    ("😌", "relieved face"),
    ("😍", "smiling face with heart-eyes"),
    ("😎", "smiling face with sunglasses"),
    ("😏", "smirking face"),
    ("😐", "neutral face"),
    ("😑", "expressionless face"),
    ("😒", "unamused face"),
    ("😓", "downcast face with sweat"),
    ("😔", "pensive face"),
    ("😕", "confused face"),
    ("😖", "confounded face"),
    ("😗", "kissing face"),
    ("😘", "face blowing a kiss"),
    ("😙", "kissing face with smiling eyes"),
    ("😚", "kissing face with closed eyes"),
    ("😛", "face with tongue"),
    ("😜", "winking face with tongue"),
    ("😝", "squinting face with tongue"),
    ("😞", "disappointed face"),
    ("😟", "worried face"),
    ("😠", "angry face"),
    ("😡", "enraged face"),
    ("😢", "crying face"),
    ("😣", "persevering face"),
    ("😤", "face with steam from nose"),
    ("😥", "sad but relieved face"),
    ("😦", "frowning face with open mouth"),
    ("😧", "anguished face"),
    ("😨", "fearful face"),
    ("😩", "weary face"),
    ("😪", "sleepy face"),
    ("😫", "tired face"),
    ("😬", "grimacing face"),
    ("😭", "loudly crying face"),
    ("😮‍💨", "face exhaling"),
    ("😮", "face with open mouth"),
    ("😯", "hushed face"),
    ("😰", "anxious face with sweat"),
    ("😱", "face screaming in fear"),
    ("😲", "astonished face"),
    ("😳", "flushed face"),
    ("😴", "sleeping face"),
    ("😵‍💫", "face with spiral eyes"),
    ("😵", "face with crossed-out eyes"),
    ("😶‍🌫️", "face in clouds"),
    ("😶", "face without mouth"),
    ("😷", "face with medical mask"),
    ("😸", "grinning cat with smiling eyes"),
    ("😹", "cat with tears of joy"),
    ("😺", "grinning cat"),
    ("😻", "smiling cat with heart-eyes"),
    ("😼", "cat with wry smile"),
    ("😽", "kissing cat"),
    ("😾", "pouting cat"),
    ("😿", "crying cat"),
    ("🙀", "weary cat"),
    ("🙁", "slightly frowning face"),
    ("🙂‍↔️", "head shaking horizontally"),
    ("🙂‍↕️", "head shaking vertically"),
    ("🙂", "slightly smiling face"),
    ("🙃", "upside-down face"),
    ("🙄", "face with rolling eyes"),
    ("🙅‍♀️", "woman gesturing NO"),
    ("🙅‍♂️", "man gesturing NO"),
    ("🙅", "person gesturing NO"),
    ("🙆‍♀️", "woman gesturing OK"),
    ("🙆‍♂️", "man gesturing OK"),
    ("🙆", "person gesturing OK"),
    ("🙇‍♀️", "woman bowing"),
    ("🙇‍♂️", "man bowing"),
    ("🙇", "person bowing"),
    ("🙈", "see-no-evil monkey"),
    ("🙉", "hear-no-evil monkey"),
    ("🙊", "speak-no-evil monkey"),
    ("🙋‍♀️", "woman raising hand"),
    ("🙋‍♂️", "man raising hand"),
    ("🙋", "person raising hand"),
    ("🙌", "raising hands"),
    ("🙍‍♀️", "woman frowning"),
    ("🙍‍♂️", "man frowning"),
    ("🙍", "person frowning"),
    ("🙎‍♀️", "woman pouting"),
    ("🙎‍♂️", "man pouting"),
    ("🙎", "person pouting"),
    ("🙏", "folded hands"),
    ("🚀", "rocket"),
    ("🚁", "helicopter"),
    ("🚂", "locomotive"),
    ("🚃", "railway car"),
    ("🚄", "high-speed train"),
    ("🚅", "bullet train"),
    ("🚆", "train"),
    ("🚇", "metro"),
    ("🚈", "light rail"),
    ("🚉", "station"),
    ("🚊", "tram"),
    ("🚋", "tram car"),
    ("🚌", "bus"),
    ("🚍", "oncoming bus"),
    ("🚎", "trolleybus"),
    ("🚏", "bus stop"),
    ("🚐", "minibus"),
    ("🚑", "ambulance"),
    ("🚒", "fire engine"),
    ("🚓", "police car"),
    ("🚔", "oncoming police car"),
    ("🚕", "taxi"),
    ("🚖", "oncoming taxi"),
    ("🚗", "automobile"),
    ("🚘", "oncoming automobile"),
    ("🚙", "sport utility vehicle"),
    ("🚚", "delivery truck"),
    ("🚛", "articulated lorry"),
    ("🚜", "tractor"),
    ("🚝", "monorail"),
    ("🚞", "mountain railway"),
    ("🚟", "suspension railway"),
    ("🚠", "mountain cableway"),
    ("🚡", "aerial tramway"),
    ("🚢", "ship"),
    ("🚣‍♀️", "woman rowing boat"),
    ("🚣‍♂️", "man rowing boat"),
    ("🚣", "person rowing boat"),
    ("🚤", "speedboat"),
    ("🚥", "horizontal traffic light"),
    ("🚦", "vertical traffic light"),
    ("🚧", "construction"),
    ("🚨", "police car light"),
    ("🚩", "triangular flag"),
    ("🚪", "door"),
    ("🚫", "prohibited"),
    ("🚬", "cigarette"),
    ("🚭", "no smoking"),
    ("🚮", "litter in bin sign"),
    ("🚯", "no littering"),
    ("🚰", "potable water"),
    ("🚱", "non-potable water"),
    ("🚲", "bicycle"),
    ("🚳", "no bicycles"),
    ("🚴‍♀️", "woman biking"),
    ("🚴‍♂️", "man biking"),
    ("🚴", "person biking"),
    ("🚵‍♀️", "woman mountain biking"),
    ("🚵‍♂️", "man mountain biking"),
    ("🚵", "person mountain biking"),
    ("🚶‍♀️‍➡️", "woman walking facing right"),
    ("🚶‍♀️", "woman walking"),
    ("🚶‍♂️‍➡️", "man walking facing right"),
    ("🚶‍♂️", "man walking"),
    ("🚶‍➡️", "person walking facing right"),
    ("🚶", "person walking"),
    ("🚷", "no pedestrians"),
    ("🚸", "children crossing"),
    ("🚹", "men’s room"),
    ("🚺", "women’s room"),
    ("🚻", "restroom"),
    ("🚼", "baby symbol"),
    ("🚽", "toilet"),
    ("🚾", "water closet"),
    ("🚿", "shower"),
    ("🛀", "person taking bath"),
    ("🛁", "bathtub"),
    ("🛂", "passport control"),
    ("🛃", "customs"),
    ("🛄", "baggage claim"),
    ("🛅", "left luggage"),
    ("🛋", "couch and lamp"),
    ("🛌", "person in bed"),
    ("🛍", "shopping bags"),
    ("🛎", "bellhop bell"),
    ("🛏", "bed"),
    ("🛐", "place of worship"),
    ("🛑", "stop sign"),
    ("🛒", "shopping cart"),
    ("🛕", "hindu temple"),
    ("🛖", "hut"),
    ("🛗", "elevator"),
    ("🛜", "wireless"),
    ("🛝", "playground slide"),
    ("🛞", "wheel"),
    ("🛟", "ring buoy"),
    ("🛠", "hammer and wrench"),
    ("🛡", "shield"),
    ("🛢", "oil drum"),
    ("🛣", "motorway"),
    ("🛤", "railway track"),
    ("🛥", "motor boat"),
    ("🛩", "small airplane"),
    ("🛫", "airplane departure"),
    ("🛬", "airplane arrival"),
    ("🛰", "satellite"),
    ("🛳", "passenger ship"),
    ("🛴", "kick scooter"),
    ("🛵", "motor scooter"),
    ("🛶", "canoe"),
    ("🛷", "sled"),
    ("🛸", "flying saucer"),
    ("🛹", "skateboard"),
    ("🛺", "auto rickshaw"),
    ("🛻", "pickup truck"),
    ("🛼", "roller skate"),
    ("🟠", "orange circle"),
    ("🟡", "yellow circle"),
    ("🟢", "green circle"),
    ("🟣", "purple circle"),
    ("🟤", "brown circle"),
    ("🟥", "red square"),
    ("🟦", "blue square"),
    ("🟧", "orange square"),
    ("🟨", "yellow square"),
    ("🟩", "green square"),
    ("🟪", "purple square"),
    ("🟫", "brown square"),
    ("🟰", "heavy equals sign"),
    ("🤌", "pinched fingers"),
    ("🤍", "white heart"),
    ("🤎", "brown heart"),
    ("🤏", "pinching hand"),
    ("🤐", "zipper-mouth face"),
    ("🤑", "money-mouth face"),
    ("🤒", "face with thermometer"),
    ("🤓", "nerd face"),
    ("🤔", "thinking face"),
    ("🤕", "face with head-bandage"),
    ("🤖", "robot"),
    ("🤗", "smiling face with open hands"),
    ("🤘", "sign of the horns"),
    ("🤙", "call me hand"),
    ("🤚", "raised back of hand"),
    ("🤛", "left-facing fist"),
    ("🤜", "right-facing fist"),
    ("🤝", "handshake"),
    ("🤞", "crossed fingers"),
    ("🤟", "love-you gesture"),
    ("🤠", "cowboy hat face"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤤", "drooling face"),
    ("🤥", "lying face"),
    ("🤦‍♀️", "woman facepalming"),
    ("🤦‍♂️", "man facepalming"),
    ("🤦", "person facepalming"),
    ("🤧", "sneezing face"),
    ("🤨", "face with raised eyebrow"),
    ("🤩", "star-struck"),
    ("🤪", "zany face"),
    ("🤫", "shushing face"),
    ("🤬", "face with symbols on mouth"),
    ("🤭", "face with hand over mouth"),
    ("🤮", "face vomiting"),
    ("🤯", "exploding head"),
    ("🤰", "pregnant woman"),
    ("🤱", "breast-feeding"),
    ("🤲", "palms up together"),
    ("🤳", "selfie"),
    ("🤴", "prince"),
    ("🤵‍♀️", "woman in tuxedo"),
    ("🤵‍♂️", "man in tuxedo"),
    ("🤵", "person in tuxedo"),
    ("🤶", "Mrs. Claus"),
    ("🤷‍♀️", "woman shrugging"),
    ("🤷‍♂️", "man shrugging"),
    ("🤷", "person shrugging"),
    ("🤸‍♀️", "woman cartwheeling"),
    ("🤸‍♂️", "man cartwheeling"),
    ("🤸", "person cartwheeling"),
    ("🤹‍♀️", "woman juggling"),
    ("🤹‍♂️", "man juggling"),
    ("🤹", "person juggling"),
    ("🤺", "person fencing"),
    ("🤼‍♀️", "women wrestling"),
    ("🤼‍♂️", "men wrestling"),
    ("🤼", "people wrestling"),
    ("🤽‍♀️", "woman playing water polo"),
    ("🤽‍♂️", "man playing water polo"),
    ("🤽", "person playing water polo"),
    ("🤾‍♀️", "woman playing handball"),
    ("🤾‍♂️", "man playing handball"),
    ("🤾", "person playing handball"),
    ("🤿", "diving mask"),
    ("🥀", "wilted flower"),
    ("🥁", "drum"),
    ("🥂", "clinking glasses"),
    ("🥃", "tumbler glass"),
    ("🥄", "spoon"),
    ("🥅", "goal net"),
    ("🥇", "1st place medal"),
    ("🥈", "2nd place medal"),
    ("🥉", "3rd place medal"),
    ("🥊", "boxing glove"),
    ("🥋", "martial arts uniform"),
    ("🥌", "curling stone"),
    ("🥍", "lacrosse"),
    ("🥎", "softball"),
    ("🥏", "flying disc"),
    ("🥐", "croissant"),
    ("🥑", "avocado"),
    ("🥒", "cucumber"),
    ("🥓", "bacon"),
    ("🥔", "potato"),
    ("🥕", "carrot"),
    ("🥖", "baguette bread"),
    ("🥗", "green salad"),
    ("🥘", "shallow pan of food"),
    ("🥙", "stuffed flatbread"),
    ("🥚", "egg"),
    ("🥛", "glass of milk"),
    ("🥜", "peanuts"),
    ("🥝", "kiwi fruit"),
    ("🥞", "pancakes"),
    ("🥟", "dumpling"),
    ("🥠", "fortune cookie"),
    ("🥡", "takeout box"),
    ("🥢", "chopsticks"),
    ("🥣", "bowl with spoon"),
    ("🥤", "cup with straw"),
    ("🥥", "coconut"),
    ("🥦", "broccoli"),
    ("🥧", "pie"),
    ("🥨", "pretzel"),
    ("🥩", "cut of meat"),
    ("🥪", "sandwich"),
    ("🥫", "canned food"),
    ("🥬", "leafy green"),
    ("🥭", "mango"),
    ("🥮", "moon cake"),
    ("🥯", "bagel"),
    ("🥰", "smiling face with hearts"),
    ("🥱", "yawning face"),
    ("🥲", "smiling face with tear"),
    ("🥳", "partying face"),
    ("🥴", "woozy face"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🥷", "ninja"),
    ("🥸", "disguised face"),
    ("🥹", "face holding back tears"),
    ("🥺", "pleading face"),
    ("🥻", "sari"),
    ("🥼", "lab coat"),
    ("🥽", "goggles"),
    ("🥾", "hiking boot"),
    ("🥿", "flat shoe"),
    ("🦀", "crab"),
    ("🦁", "lion"),
    ("🦂", "scorpion"),
    ("🦃", "turkey"),
    ("🦄", "unicorn"),
    ("🦅", "eagle"),
    ("🦆", "duck"),
    ("🦇", "bat"),
    ("🦈", "shark"),
    ("🦉", "owl"),
    ("🦊", "fox"),
    ("🦋", "butterfly"),
    ("🦌", "deer"),
    ("🦍", "gorilla"),
    ("🦎", "lizard"),
    ("🦏", "rhinoceros"),
    ("🦐", "shrimp"),
    ("🦑", "squid"),
    ("🦒", "giraffe"),
    ("🦓", "zebra"),
    ("🦔", "hedgehog"),
    ("🦕", "sauropod"),
    ("🦖", "T-Rex"),
    ("🦗", "cricket"),
    ("🦘", "kangaroo"),
    ("🦙", "llama"),
    ("🦚", "peacock"),
    ("🦛", "hippopotamus"),
    ("🦜", "parrot"),
    ("🦝", "raccoon"),
    ("🦞", "lobster"),
    ("🦟", "mosquito"),
    ("🦠", "microbe"),
    ("🦡", "badger"),
    ("🦢", "swan"),
    ("🦣", "mammoth"),
    ("🦤", "dodo"),
    ("🦥", "sloth"),
    ("🦦", "otter"),
    ("🦧", "orangutan"),
    ("🦨", "skunk"),
    ("🦩", "flamingo"),
    ("🦪", "oyster"),
    ("🦫", "beaver"),
    ("🦬", "bison"),
    ("🦭", "seal"),
    ("🦮", "guide dog"),
    ("🦯", "white cane"),
    ("🦰", "red hair"),
    ("🦱", "curly hair"),
    ("🦲", "bald"),
    ("🦳", "white hair"),
    ("🦴", "bone"),
    ("🦵", "leg"),
    ("🦶", "foot"),
    ("🦷", "tooth"),
    ("🦸‍♀️", "woman superhero"),
    ("🦸‍♂️", "man superhero"),
    ("🦸", "superhero"),
    ("🦹‍♀️", "woman supervillain"),
    ("🦹‍♂️", "man supervillain"),
    ("🦹", "supervillain"),
    ("🦺", "safety vest"),
    ("🦻", "ear with hearing aid"),
    ("🦼", "motorized wheelchair"),
    ("🦽", "manual wheelchair"),
    ("🦾", "mechanical arm"),
    ("🦿", "mechanical leg"),
    ("🧀", "cheese wedge"),
    ("🧁", "cupcake"),
    ("🧂", "salt"),
    ("🧃", "beverage box"),
    ("🧄", "garlic"),
    ("🧅", "onion"),
    ("🧆", "falafel"),
    ("🧇", "waffle"),
    ("🧈", "butter"),
    ("🧉", "mate"),
    ("🧊", "ice"),
    ("🧋", "bubble tea"),
    ("🧌", "troll"),
    ("🧍‍♀️", "woman standing"),
    ("🧍‍♂️", "man standing"),
    ("🧍", "person standing"),
    ("🧎‍♀️‍➡️", "woman kneeling facing right"),
    ("🧎‍♀️", "woman kneeling"),
    ("🧎‍♂️‍➡️", "man kneeling facing right"),
    ("🧎‍♂️", "man kneeling"),
    ("🧎‍➡️", "person kneeling facing right"),
    ("🧎", "person kneeling"),
    ("🧏‍♀️", "deaf woman"),
    ("🧏‍♂️", "deaf man"),
    ("🧏", "deaf person"),
    ("🧐", "face with monocle"),
    ("🧑‍🌾", "farmer"),
    ("🧑‍🍳", "cook"),
    ("🧑‍🍼", "person feeding baby"),
    ("🧑‍🎄", "Mx Claus"),
    ("🧑‍🎓", "student"),
    ("🧑‍🎤", "singer"),
    ("🧑‍🎨", "artist"),
    ("🧑‍🏫", "teacher"),
    ("🧑‍🏭", "factory worker"),
    ("🧑‍💻", "technologist"),
    ("🧑‍💼", "office worker"),
    ("🧑‍🔧", "mechanic"),
    ("🧑‍🔬", "scientist"),
    ("🧑‍🚀", "astronaut"),
    ("🧑‍🚒", "firefighter"),
    ("🧑‍🤝‍🧑", "people holding hands"),
    ("🧑‍🦯‍➡️", "person with white cane facing right"),
    ("🧑‍🦯", "person with white cane"),
    ("🧑‍🦰", "person: red hair"),
    ("🧑‍🦱", "person: curly hair"),
    ("🧑‍🦲", "person: bald"),
    ("🧑‍🦳", "person: white hair"),
    ("🧑‍🦼‍➡️", "person in motorized wheelchair facing right"),
    ("🧑‍🦼", "person in motorized wheelchair"),
    ("🧑‍🦽‍➡️", "person in manual wheelchair facing right"),
    ("🧑‍🦽", "person in manual wheelchair"),
    ("🧑‍🧑‍🧒‍🧒", "family: adult, adult, child, child"),
    ("🧑‍🧑‍🧒", "family: adult, adult, child"),
    ("🧑‍🧒‍🧒", "family: adult, child, child"),
    ("🧑‍🧒", "family: adult, child"),
    ("🧑‍⚕️", "health worker"),
    ("🧑‍⚖️", "judge"),
    ("🧑‍✈️", "pilot"),
    ("🧑", "person"),
    ("🧒", "child"),
    ("🧓", "older person"),
    ("🧔‍♀️", "woman: beard"),
    ("🧔‍♂️", "man: beard"),
    ("🧔", "person: beard"),
    ("🧕", "woman with headscarf"),
    ("🧖‍♀️", "woman in steamy room"),
    ("🧖‍♂️", "man in steamy room"),
    ("🧖", "person in steamy room"),
    ("🧗‍♀️", "woman climbing"),
    ("🧗‍♂️", "man climbing"),
    ("🧗", "person climbing"),
    ("🧘‍♀️", "woman in lotus position"),
    ("🧘‍♂️", "man in lotus position"),
    ("🧘", "person in lotus position"),
    ("🧙‍♀️", "woman mage"),
    ("🧙‍♂️", "man mage"),
    ("🧙", "mage"),
    ("🧚‍♀️", "woman fairy"),
    ("🧚‍♂️", "man fairy"),
    ("🧚", "fairy"),
    ("🧛‍♀️", "woman vampire"),
    ("🧛‍♂️", "man vampire"),
    ("🧛", "vampire"),
    ("🧜‍♀️", "mermaid"),
    ("🧜‍♂️", "merman"),
    ("🧜", "merperson"),
    ("🧝‍♀️", "woman elf"),
    ("🧝‍♂️", "man elf"),
    ("🧝", "elf"),
    ("🧞‍♀️", "woman genie"),
    ("🧞‍♂️", "man genie"),
    ("🧞", "genie"),
    ("🧟‍♀️", "woman zombie"),
    ("🧟‍♂️", "man zombie"),
    ("🧟", "zombie"),
    ("🧠", "brain"),
    ("🧡", "orange heart"),
    ("🧢", "billed cap"),
    ("🧣", "scarf"),
    ("🧤", "gloves"),
    ("🧥", "coat"),
    ("🧦", "socks"),
    ("🧧", "red envelope"),
    ("🧨", "firecracker"),
    ("🧩", "puzzle piece"),
    ("🧪", "test tube"),
    ("🧫", "petri dish"),
    ("🧬", "dna"),
    ("🧭", "compass"),
    ("🧮", "abacus"),
    ("🧯", "fire extinguisher"),
    ("🧰", "toolbox"),
    ("🧱", "brick"),
    ("🧲", "magnet"),
    ("🧳", "luggage"),
    ("🧴", "lotion bottle"),
    ("🧵", "thread"),
    ("🧶", "yarn"),
    ("🧷", "safety pin"),
    ("🧸", "teddy bear"),
    ("🧹", "broom"),
    ("🧺", "basket"),
    ("🧻", "roll of paper"),
    ("🧼", "soap"),
    ("🧽", "sponge"),
    ("🧾", "receipt"),
    ("🧿", "nazar amulet"),
    ("🩰", "ballet shoes"),
    ("🩱", "one-piece swimsuit"),
    ("🩲", "briefs"),
    ("🩳", "shorts"),
    ("🩴", "thong sandal"),
    ("🩵", "light blue heart"),
    ("🩶", "grey heart"),
    ("🩷", "pink heart"),
    ("🩸", "drop of blood"),
    ("🩹", "adhesive bandage"),
    ("🩺", "stethoscope"),
    ("🩻", "x-ray"),
    ("🩼", "crutch"),
    ("🪀", "yo-yo"),
    ("🪁", "kite"),
    ("🪂", "parachute"),
    ("🪃", "boomerang"),
    ("🪄", "magic wand"),
    ("🪅", "piñata"),
    ("🪆", "nesting dolls"),
    ("🪇", "maracas"),
    ("🪈", "flute"),
    ("🪉", "harp"),
    ("🪏", "shovel"),
    ("🪐", "ringed planet"),
    ("🪑", "chair"),
    ("🪒", "razor"),
    ("🪓", "axe"),
    ("🪔", "diya lamp"),
    ("🪕", "banjo"),
    ("🪖", "military helmet"),
    ("🪗", "accordion"),
    ("🪘", "long drum"),
    ("🪙", "coin"),
    ("🪚", "carpentry saw"),
    ("🪛", "screwdriver"),
    ("🪜", "ladder"),
    ("🪝", "hook"),
    ("🪞", "mirror"),
    ("🪟", "window"),
    ("🪠", "plunger"),
    ("🪡", "sewing needle"),
    ("🪢", "knot"),
    ("🪣", "bucket"),
    ("🪤", "mouse trap"),
    ("🪥", "toothbrush"),
    ("🪦", "headstone"),
    ("🪧", "placard"),
    ("🪨", "rock"),
    ("🪩", "mirror ball"),
    ("🪪", "identification card"),
    ("🪫", "low battery"),
    ("🪬", "hamsa"),
    ("🪭", "folding hand fan"),
    ("🪮", "hair pick"),
    ("🪯", "khanda"),
    ("🪰", "fly"),
    ("🪱", "worm"),
    ("🪲", "beetle"),
    ("🪳", "cockroach"),
    ("🪴", "potted plant"),
    ("🪵", "wood"),
    ("🪶", "feather"),
    ("🪷", "lotus"),
    ("🪸", "coral"),
    ("🪹", "empty nest"),
    ("🪺", "nest with eggs"),
    ("🪻", "hyacinth"),
    ("🪼", "jellyfish"),
    ("🪽", "wing"),
    ("🪾", "leafless tree"),
    ("🪿", "goose"),
    ("🫀", "anatomical heart"),
    ("🫁", "lungs"),
    ("🫂", "people hugging"),
    ("🫃", "pregnant man"),
    ("🫄", "pregnant person"),
    ("🫅", "person with crown"),
    ("🫆", "fingerprint"),
    ("🫎", "moose"),
    ("🫏", "donkey"),
    ("🫐", "blueberries"),
    ("🫑", "bell pepper"),
    ("🫒", "olive"),
    ("🫓", "flatbread"),
    ("🫔", "tamale"),
    ("🫕", "fondue"),
    ("🫖", "teapot"),
    ("🫗", "pouring liquid"),
    ("🫘", "beans"),
    ("🫙", "jar"),
    ("🫚", "ginger root"),
    ("🫛", "pea pod"),
    ("🫜", "root vegetable"),
    ("🫟", "splatter"),
    ("🫠", "melting face"),
    ("🫡", "saluting face"),
    ("🫢", "face with open eyes and hand over mouth"),
    ("🫣", "face with peeking eye"),
    ("🫤", "face with diagonal mouth"),
    ("🫥", "dotted line face"),
    ("🫦", "biting lip"),
    ("🫧", "bubbles"),
    ("🫨", "shaking face"),
    ("🫩", "face with bags under eyes"),
    ("🫰", "hand with index finger and thumb crossed"),
    ("🫱", "rightwards hand"),
    ("🫲", "leftwards hand"),
    ("🫳", "palm down hand"),
    ("🫴", "palm up hand"),
    ("🫵", "index pointing at the viewer"),
    ("🫶", "heart hands"),
    ("🫷", "leftwards pushing hand"),
    ("🫸", "rightwards pushing hand"),
    ("‼", "double exclamation mark"),
    ("⁉", "exclamation question mark"),
    ("™", "trade mark"),
    ("ℹ", "information"),
    ("↔", "left-right arrow"),
    ("↕", "up-down arrow"),
    ("↖", "up-left arrow"),
    ("↗", "up-right arrow"),
    ("↘", "down-right arrow"),
    ("↙", "down-left arrow"),
    ("↩", "right arrow curving left"),
    ("↪", "left arrow curving right"),
    ("⌚", "watch"),
    ("⌛", "hourglass done"),
    ("⌨", "keyboard"),
    ("⏏", "eject button"),
    ("⏩", "fast-forward button"),
    ("⏪", "fast reverse button"),
    ("⏫", "fast up button"),
    ("⏬", "fast down button"),
    ("⏭", "next track button"),
    ("⏮", "last track button"),
    ("⏯", "play or pause button"),
    ("⏰", "alarm clock"),
    ("⏱", "stopwatch"),
    ("⏲", "timer clock"),
    ("⏳", "hourglass not done"),
    ("⏸", "pause button"),
    ("⏹", "stop button"),
    ("⏺", "record button"),
    ("Ⓜ", "circled M"),
    ("▪", "black small square"),
    ("▫", "white small square"),
    ("▶", "play button"),
    ("◀", "reverse button"),
    ("◻", "white medium square"),
    ("◼", "black medium square"),
    ("◽", "white medium-small square"),
    ("◾", "black medium-small square"),
    ("☀", "sun"),
    ("☁", "cloud"),
    ("☂", "umbrella"),
    ("☃", "snowman"),
    ("☄", "comet"),
    ("☎", "telephone"),
    ("☑", "check box with check"),
    ("☔", "umbrella with rain drops"),
    ("☕", "hot beverage"),
    ("☘", "shamrock"),
    ("☝", "index pointing up"),
    ("☠", "skull and crossbones"),
    ("☢", "radioactive"),
    ("☣", "biohazard"),
    ("☦", "orthodox cross"),
    ("☪", "star and crescent"),
    ("☮", "peace symbol"),
    ("☯", "yin yang"),
    ("☸", "wheel of dharma"),
    ("☹", "frowning face"),
    ("☺", "smiling face"),
    ("♀", "female sign"),
    ("♂", "male sign"),
    ("♈", "Aries"),
    ("♉", "Taurus"),
    ("♊", "Gemini"),
    ("♋", "Cancer"),
    ("♌", "Leo"),
    ("♍", "Virgo"),
    ("♎", "Libra"),
    ("♏", "Scorpio"),
    ("♐", "Sagittarius"),
    ("♑", "Capricorn"),
    ("♒", "Aquarius"),
    ("♓", "Pisces"),
    ("♟", "chess pawn"),
    ("♠", "spade suit"),
    ("♣", "club suit"),
    ("♥", "heart suit"),
    ("♦", "diamond suit"),
    ("♨", "hot springs"),
    ("♻", "recycling symbol"),
    ("♾", "infinity"),
    ("♿", "wheelchair symbol"),
    ("⚒", "hammer and pick"),
    ("⚓", "anchor"),
    ("⚔", "crossed swords"),
    ("⚕", "medical symbol"),
    ("⚖", "balance scale"),
    ("⚗", "alembic"),
    ("⚙", "gear"),
    ("⚛", "atom symbol"),
    ("⚜", "fleur-de-lis"),
    ("⚠", "warning"),
    ("⚡", "high voltage"),
    ("⚧", "transgender symbol"),
    ("⚪", "white circle"),
    ("⚫", "black circle"),
    ("⚰", "coffin"),
    ("⚱", "funeral urn"),
    ("⚽", "soccer ball"),
    ("⚾", "baseball"),
    ("⛄", "snowman without snow"),
    ("⛅", "sun behind cloud"),
    ("⛈", "cloud with lightning and rain"),
    ("⛎", "Ophiuchus"),
    ("⛏", "pick"),
    ("⛑", "rescue worker’s helmet"),
    ("⛓️‍💥", "broken chain"),
    ("⛓", "chains"),
    ("⛔", "no entry"),
    ("⛩", "shinto shrine"),
    ("⛪", "church"),
    ("⛰", "mountain"),
    ("⛱", "umbrella on ground"),
    ("⛲", "fountain"),
    ("⛳", "flag in hole"),
    ("⛴", "ferry"),
    ("⛵", "sailboat"),
    ("⛷", "skier"),
    ("⛸", "ice skate"),
    ("⛹️‍♀️", "woman bouncing ball"),
    ("⛹️‍♂️", "man bouncing ball"),
    ("⛹", "person bouncing ball"),
    ("⛺", "tent"),
    ("⛽", "fuel pump"),
    ("✂", "scissors"),
    ("✅", "check mark button"),
    ("✈", "airplane"),
    ("✉", "envelope"),
    ("✊", "raised fist"),
    ("✋", "raised hand"),
    ("✌", "victory hand"),
    ("✍", "writing hand"),
    ("✏", "pencil"),
    ("✒", "black nib"),
    ("✔", "check mark"),
    ("✖", "multiply"),
    ("✝", "latin cross"),
    ("✡", "star of David"),
    ("✨", "sparkles"),
    ("✳", "eight-spoked asterisk"),
    ("✴", "eight-pointed star"),
    ("❄", "snowflake"),
    ("❇", "sparkle"),
    ("❌", "cross mark"),
    ("❎", "cross mark button"),
    ("❓", "red question mark"),
    ("❔", "white question mark"),
    ("❕", "white exclamation mark"),
    ("❗", "red exclamation mark"),
    ("❣", "heart exclamation"),
    ("❤️‍🔥", "heart on fire"),
    ("❤️‍🩹", "mending heart"),
    ("❤", "red heart"),
    ("➕", "plus"),
    ("➖", "minus"),
    ("➗", "divide"),
    ("➡", "right arrow"),
    ("➰", "curly loop"),
    ("➿", "double curly loop"),
    ("⤴", "right arrow curving up"),
    ("⤵", "right arrow curving down"),
    ("⬅", "left arrow"),
    ("⬆", "up arrow"),
    ("⬇", "down arrow"),
    ("⬛", "black large square"),
    ("⬜", "white large square"),
    ("⭐", "star"),
    ("⭕", "hollow red circle"),
    ("〰", "wavy dash"),
    ("〽", "part alternation mark"),
    ("㊗", "Japanese “congratulations” button"),
    ("㊙", "Japanese “secret” button"),
];
