use std::{
    collections::{BTreeMap, BTreeSet},
    path::Path,
};

use super::{
    model::{EventKind, CONTRACT_MODEL_VERSION},
    registry::{
        registry, schema_fingerprint, shared_types, ContractFamilySpec, ContractPropSpec,
        ContractPropTypeKind, ContractSharedTypeKind, ContractSharedTypeSpec,
    },
};

const HTML_HOST_TAGS: [&str; 34] = [
    "a", "article", "aside", "button", "code", "dialog", "div", "em", "footer", "form", "h1", "h2",
    "h3", "h4", "h5", "h6", "header", "hr", "img", "input", "kbd", "label", "li", "main", "nav",
    "ol", "p", "pre", "progress", "section", "small", "span", "strong", "ul",
];

const HTML_CONTAINER_TAGS: [&str; 12] = [
    "article", "aside", "div", "footer", "form", "header", "li", "main", "nav", "ol", "section",
    "ul",
];

const HTML_TEXT_TAGS: [&str; 14] = [
    "a", "code", "em", "h1", "h2", "h3", "h4", "h5", "h6", "p", "pre", "small", "span", "strong",
];

const HTML_EXPLICIT_FAMILY_TAGS: [(&str, &str); 6] = [
    ("button", "button"),
    ("dialog", "dialogue-modal"),
    ("hr", "separator"),
    ("img", "image"),
    ("kbd", "kbd"),
    ("progress", "progress"),
];

const LEGACY_FAMILY_ALIASES: [(&str, &str); 18] = [
    ("box", "sized-box"),
    ("sizedbox", "sized-box"),
    ("dialogue", "dialogue-modal"),
    ("dialogueModal", "dialogue-modal"),
    ("dropdown", "dropdown-menu"),
    ("dropdownMenu", "dropdown-menu"),
    ("filetree", "file-tree"),
    ("imageTile", "image-tile"),
    ("iconToolbar", "icon-toolbar"),
    ("radioGroup", "radio-group"),
    ("toast", "toast-viewport"),
    ("img", "image"),
    ("section", "column"),
    ("main", "column"),
    ("header", "column"),
    ("footer", "column"),
    ("nav", "column"),
    ("article", "column"),
];

pub fn typescript_declarations() -> String {
    let all_families = registry();
    let all_shared_types = shared_types();
    let node_common = all_shared_types
        .iter()
        .find(|shared| shared.name == "node_common")
        .expect("node_common shared type should exist");

    let shared_type_names = all_shared_types
        .iter()
        .map(|shared| shared.name.to_owned())
        .collect::<BTreeSet<_>>();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p clay-jsx-runtime --bin generate-contract-types`\n",
    );
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("/* eslint-disable */\n\n");

    out.push_str(&format!(
        "type ClayContractModelVersion = {CONTRACT_MODEL_VERSION};\n"
    ));
    out.push_str(&format!(
        "type ClayContractSchemaFingerprint = \"{}\";\n\n",
        schema_fingerprint()
    ));

    out.push_str("type ClayContractFamily =\n");
    for family in all_families {
        out.push_str(&format!("  | \"{}\"\n", family.id.as_str()));
    }
    out.push_str(";\n\n");

    emit_shared_types(&mut out, all_shared_types, &shared_type_names);
    emit_event_support_types(&mut out);
    emit_family_types(&mut out, all_families, node_common, &shared_type_names);
    emit_intrinsic_types(&mut out, all_families);
    emit_runtime_module_declarations(&mut out, all_families);

    out
}

pub fn write_typescript_declarations(path: impl AsRef<Path>) -> std::io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, typescript_declarations())
}

fn emit_shared_types(
    out: &mut String,
    all_shared_types: &[ContractSharedTypeSpec],
    shared_type_names: &BTreeSet<String>,
) {
    out.push_str("type ClayNode = import(\"react\").ReactNode;\n");
    out.push_str("type ClayRecord = Readonly<Record<string, unknown>>;\n\n");

    for shared in all_shared_types {
        let shared_type_name = shared_type_ts_name(shared.name);
        match shared.kind {
            ContractSharedTypeKind::Enum => {
                if shared.variants.is_empty() {
                    out.push_str(&format!("type {shared_type_name} = string;\n\n"));
                    continue;
                }
                out.push_str(&format!("type {shared_type_name} =\n"));
                for variant in shared.variants {
                    out.push_str(&format!("  | \"{}\"\n", variant.id));
                }
                out.push_str(";\n\n");
            }
            ContractSharedTypeKind::Object => {
                out.push_str(&format!("interface {shared_type_name} {{\n"));
                emit_props(
                    out,
                    shared.fields,
                    shared_type_names,
                    EmitMode::SchemaRequired,
                    false,
                );
                out.push_str("}\n\n");
            }
        }
    }
}

fn emit_event_support_types(out: &mut String) {
    out.push_str("type ClayEventKind =\n");
    out.push_str("  | \"clicked\"\n");
    out.push_str("  | \"changed\"\n");
    out.push_str("  | \"submitted\"\n");
    out.push_str("  | \"selected\"\n");
    out.push_str("  | \"toggled\"\n");
    out.push_str("  | \"confirmed\"\n");
    out.push_str("  | \"cancelled\"\n");
    out.push_str("  | \"opened\"\n");
    out.push_str("  | \"closed\"\n");
    out.push_str("  | \"command_invoked\";\n\n");

    out.push_str("interface ClayEvent {\n");
    out.push_str("  readonly kind?: ClayEventKind;\n");
    out.push_str("  readonly value?: unknown;\n");
    out.push_str("  readonly metadata?: Readonly<Record<string, unknown>>;\n");
    out.push_str("  readonly node_id?: string;\n");
    out.push_str("  readonly action_id?: string;\n");
    out.push_str("  readonly [key: string]: unknown;\n");
    out.push_str("}\n\n");

    out.push_str(
        "type ClayEventHandler<TValue = unknown> = (event: ClayEvent, value?: TValue) => void;\n\n",
    );

    out.push_str("interface ClayMotionValues {\n");
    out.push_str("  readonly opacity?: number;\n");
    out.push_str("  readonly x?: number;\n");
    out.push_str("  readonly y?: number;\n");
    out.push_str("  readonly scale?: number;\n");
    out.push_str("  readonly scaleX?: number;\n");
    out.push_str("  readonly scaleY?: number;\n");
    out.push_str("  readonly rotate?: number;\n");
    out.push_str("  readonly width?: number;\n");
    out.push_str("  readonly height?: number;\n");
    out.push_str("  readonly gap?: number;\n");
    out.push_str("  readonly paddingX?: number;\n");
    out.push_str("  readonly paddingY?: number;\n");
    out.push_str("  readonly cornerRadius?: number;\n");
    out.push_str("}\n\n");

    out.push_str("interface ClayMotionTransition {\n");
    out.push_str("  readonly type?: \"tween\";\n");
    out.push_str("  readonly duration?: number;\n");
    out.push_str("  readonly delay?: number;\n");
    out.push_str("  readonly ease?: \"linear\" | \"easeIn\" | \"easeOut\" | \"easeInOut\";\n");
    out.push_str("}\n\n");

    out.push_str("interface ClayMotionAuthoringProps {\n");
    out.push_str("  readonly initial?: ClayMotionValues;\n");
    out.push_str("  readonly animate?: ClayMotionValues;\n");
    out.push_str("  readonly transition?: ClayMotionTransition;\n");
    out.push_str("  readonly exit?: ClayMotionValues;\n");
    out.push_str("  readonly whileHover?: ClayMotionValues;\n");
    out.push_str("  readonly whileTap?: ClayMotionValues;\n");
    out.push_str("  readonly whileFocus?: ClayMotionValues;\n");
    out.push_str("  readonly whileInView?: ClayMotionValues;\n");
    out.push_str("}\n\n");

    out.push_str("type ClayIdentityNodeId = { readonly id: string } | { readonly nodeId: string } | { readonly node_id: string };\n\n");
}

fn emit_family_types(
    out: &mut String,
    all_families: &[ContractFamilySpec],
    node_common: &ContractSharedTypeSpec,
    shared_type_names: &BTreeSet<String>,
) {
    for family in all_families {
        let family_name = family.id.as_str();
        let family_type_name = family_props_type_name(family_name);
        let family_base_type_name = format!("{family_type_name}Base");

        out.push_str(&format!("interface {family_base_type_name} {{\n"));
        out.push_str(&format!("  readonly \"data-slot\"?: \"{family_name}\";\n"));
        out.push_str(&format!("  readonly dataSlot?: \"{family_name}\";\n"));
        out.push_str("  readonly role?: string;\n");
        out.push_str("  readonly type?: string;\n");

        if family.includes_common_props {
            emit_props(
                out,
                node_common.fields,
                shared_type_names,
                EmitMode::AllOptional,
                true,
            );
        }
        emit_props(
            out,
            family.props,
            shared_type_names,
            EmitMode::AllOptional,
            true,
        );

        let mut handler_names = BTreeSet::new();
        handler_names.insert("onEvent");
        for event in family.events {
            for handler_name in event_handler_names(event.kind) {
                handler_names.insert(handler_name);
            }
        }
        for handler_name in handler_names {
            out.push_str(&format!("  readonly {handler_name}?: ClayEventHandler;\n"));
        }

        out.push_str("}\n");
        if family.id.requires_explicit_node_id() {
            out.push_str(&format!(
                "type {family_type_name} = {family_base_type_name} & ClayIdentityNodeId;\n\n"
            ));
        } else {
            out.push_str(&format!(
                "type {family_type_name} = {family_base_type_name};\n\n"
            ));
        }
    }

    out.push_str("interface ClayFamilyPropsMap {\n");
    for family in all_families {
        let family_name = family.id.as_str();
        let family_type_name = family_props_type_name(family_name);
        out.push_str(&format!(
            "  readonly \"{family_name}\": {family_type_name};\n"
        ));
    }
    out.push_str("}\n\n");

    out.push_str("type ClayAnyFamilyProps = ClayFamilyPropsMap[ClayContractFamily];\n\n");
}

fn emit_intrinsic_types(out: &mut String, all_families: &[ContractFamilySpec]) {
    out.push_str("type ClaySlotOverrideProps = { readonly \"data-slot\": ClayContractFamily } & ClayAnyFamilyProps;\n\n");

    out.push_str("interface ClayIntrinsicElements {\n");
    let mut claimed_names = BTreeSet::new();
    for family in all_families {
        let family_name = family.id.as_str();
        if HTML_HOST_TAGS.contains(&family_name) {
            continue;
        }
        let family_type_name = family_props_type_name(family_name);
        out.push_str(&format!(
            "  readonly \"{family_name}\": {family_type_name};\n"
        ));
        claimed_names.insert(family_name.to_owned());
    }

    for (alias_name, family_name) in LEGACY_FAMILY_ALIASES {
        if claimed_names.contains(alias_name) {
            continue;
        }
        let family_type_name = family_props_type_name(family_name);
        out.push_str(&format!(
            "  readonly \"{alias_name}\": {family_type_name};\n"
        ));
        claimed_names.insert(alias_name.to_owned());
    }

    for tag in HTML_HOST_TAGS {
        if claimed_names.contains(tag) {
            continue;
        }
        let tag_type = html_tag_type(tag);
        out.push_str(&format!("  readonly \"{tag}\": {tag_type};\n"));
        claimed_names.insert(tag.to_owned());
    }

    out.push_str("}\n\n");
}

fn emit_runtime_module_declarations(out: &mut String, all_families: &[ContractFamilySpec]) {
    out.push_str("declare module \"egui/jsx-runtime\" {\n");
    out.push_str("  import type { ReactElement } from \"react\";\n");
    out.push_str("  export const Fragment: unique symbol;\n");
    out.push_str("  export function jsx(type: unknown, props: unknown, key?: string | number): ReactElement;\n");
    out.push_str("  export function jsxs(type: unknown, props: unknown, key?: string | number): ReactElement;\n");
    out.push_str("  export function jsxDEV(\n");
    out.push_str("    type: unknown,\n");
    out.push_str("    props: unknown,\n");
    out.push_str("    key: string | number | undefined,\n");
    out.push_str("    isStaticChildren: boolean,\n");
    out.push_str("    source: unknown,\n");
    out.push_str("    self: unknown,\n");
    out.push_str("  ): ReactElement;\n\n");

    out.push_str("  export namespace JSX {\n");
    out.push_str("    type Element = ReactElement;\n");
    out.push_str("    interface ElementChildrenAttribute {\n");
    out.push_str("      readonly children: unknown;\n");
    out.push_str("    }\n");
    out.push_str("    interface IntrinsicAttributes {\n");
    out.push_str("      readonly key?: string | number;\n");
    out.push_str("    }\n");
    out.push_str("    interface IntrinsicElements extends ClayIntrinsicElements {}\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"clay/jsx-runtime\" {\n");
    out.push_str("  export * from \"egui/jsx-runtime\";\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"egui/jsx-dev-runtime\" {\n");
    out.push_str("  export { Fragment, jsxDEV } from \"egui/jsx-runtime\";\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"clay/jsx-dev-runtime\" {\n");
    out.push_str("  export * from \"egui/jsx-dev-runtime\";\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"egui\" {\n");
    out.push_str("  import type * as React from \"react\";\n");
    out.push_str("  export type ContractFamily = ClayContractFamily;\n");
    out.push_str("  export type ContractModelVersion = ClayContractModelVersion;\n");
    out.push_str("  export type ContractSchemaFingerprint = ClayContractSchemaFingerprint;\n");
    out.push_str("  export type Event = ClayEvent;\n");
    out.push_str("  export const createContext: typeof React.createContext;\n");
    out.push_str("  export const startTransition: typeof React.startTransition;\n");
    out.push_str("  export const useContext: typeof React.useContext;\n");
    out.push_str("  export const useDeferredValue: typeof React.useDeferredValue;\n");
    out.push_str("  export const useEffect: typeof React.useEffect;\n");
    out.push_str("  export const useReducer: typeof React.useReducer;\n");
    out.push_str("  export const useRef: typeof React.useRef;\n");
    out.push_str("  export const useState: typeof React.useState;\n");
    out.push_str("  export const useSyncExternalStore: typeof React.useSyncExternalStore;\n");
    out.push_str("  export function render(node: React.ReactNode): void;\n");
    out.push_str("  export function requestRepaint(): void;\n");
    out.push_str(
        "  export function eventValue<TValue = unknown>(event: unknown): TValue | undefined;\n",
    );
    out.push_str("  export function log(level: string, message: string): void;\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"clay\" {\n");
    out.push_str("  export * from \"egui\";\n");
    out.push_str("}\n\n");

    out.push_str("declare module \"motion/react\" {\n");
    out.push_str("  import type { ReactElement, ReactNode } from \"react\";\n");
    out.push_str("  type MotionComponent<TProps> = (props: TProps & ClayMotionAuthoringProps) => ReactElement | null;\n");
    out.push_str("  type MotionByFamily = {\n");
    for family in all_families {
        let family_name = family.id.as_str();
        let family_type_name = family_props_type_name(family_name);
        out.push_str(&format!(
            "    readonly \"{family_name}\": MotionComponent<{family_type_name}>;\n"
        ));
    }
    out.push_str("  };\n");
    out.push_str("  export const motion: MotionByFamily & Record<string, MotionComponent<ClayAnyFamilyProps>>;\n");
    out.push_str(
        "  export function MotionConfig(props: { readonly children?: ReactNode }): ReactNode;\n",
    );
    out.push_str(
        "  export function AnimatePresence(props: { readonly children?: ReactNode }): ReactNode;\n",
    );
    out.push_str("}\n\n");

    out.push_str("declare module \"react/motion\" {\n");
    out.push_str("  export * from \"motion/react\";\n");
    out.push_str("}\n");
}

fn emit_props(
    out: &mut String,
    props: &[ContractPropSpec],
    shared_type_names: &BTreeSet<String>,
    mode: EmitMode,
    include_lowerer_aliases: bool,
) {
    let mut shaped = BTreeMap::new();

    for prop in props {
        let prop_type = prop_type_ts_name(prop, shared_type_names);
        let is_optional = match mode {
            EmitMode::SchemaRequired => !prop.required,
            EmitMode::AllOptional => true,
        };
        merge_prop(
            &mut shaped,
            prop.name.to_owned(),
            prop_type.clone(),
            is_optional,
        );

        let camel_alias = snake_to_camel(prop.name);
        if camel_alias != prop.name {
            merge_prop(&mut shaped, camel_alias, prop_type.clone(), true);
        }
        if include_lowerer_aliases {
            for alias in lowerer_aliases(prop.name) {
                merge_prop(&mut shaped, (*alias).to_owned(), prop_type.clone(), true);
            }
        }
    }

    for (name, prop) in shaped {
        let key = ts_prop_key(&name);
        let optional_marker = if prop.optional { "?" } else { "" };
        out.push_str(&format!(
            "  readonly {key}{optional_marker}: {};\n",
            prop.ty
        ));
    }
}

fn merge_prop(target: &mut BTreeMap<String, TsProp>, name: String, ty: String, optional: bool) {
    if let Some(existing) = target.get_mut(&name) {
        if existing.ty != ty {
            existing.ty = format!("{} | {}", existing.ty, ty);
        }
        existing.optional = existing.optional || optional;
        return;
    }
    target.insert(name, TsProp { ty, optional });
}

fn prop_type_ts_name(prop: &ContractPropSpec, shared_type_names: &BTreeSet<String>) -> String {
    match prop.kind {
        ContractPropTypeKind::String => "string".to_owned(),
        ContractPropTypeKind::StringList => "readonly string[]".to_owned(),
        ContractPropTypeKind::StringMap => "Readonly<Record<string, string>>".to_owned(),
        ContractPropTypeKind::Boolean => "boolean".to_owned(),
        ContractPropTypeKind::Number => "number".to_owned(),
        ContractPropTypeKind::Enum | ContractPropTypeKind::Object => prop
            .type_name
            .map(|type_name| {
                if shared_type_names.contains(type_name) {
                    shared_type_ts_name(type_name)
                } else {
                    "ClayRecord".to_owned()
                }
            })
            .unwrap_or_else(|| "ClayRecord".to_owned()),
        ContractPropTypeKind::ObjectList => prop
            .type_name
            .map(|type_name| {
                let inner = if shared_type_names.contains(type_name) {
                    shared_type_ts_name(type_name)
                } else {
                    "ClayRecord".to_owned()
                };
                format!("readonly {inner}[]")
            })
            .unwrap_or_else(|| "readonly ClayRecord[]".to_owned()),
        ContractPropTypeKind::Node => "ClayNode".to_owned(),
        ContractPropTypeKind::NodeList => "readonly ClayNode[]".to_owned(),
    }
}

fn family_props_type_name(family_name: &str) -> String {
    format!("Clay{}Props", kebab_to_pascal(family_name))
}

fn shared_type_ts_name(type_name: &str) -> String {
    format!("Clay{}", snake_or_kebab_to_pascal(type_name))
}

fn snake_or_kebab_to_pascal(value: &str) -> String {
    value
        .split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let Some(first) = chars.next() else {
                return String::new();
            };
            let mut out = String::new();
            out.push(first.to_ascii_uppercase());
            out.extend(chars);
            out
        })
        .collect::<String>()
}

fn kebab_to_pascal(value: &str) -> String {
    snake_or_kebab_to_pascal(value)
}

fn snake_to_camel(value: &str) -> String {
    let mut out = String::new();
    let mut uppercase_next = false;
    for ch in value.chars() {
        if ch == '_' {
            uppercase_next = true;
            continue;
        }
        if uppercase_next {
            out.push(ch.to_ascii_uppercase());
            uppercase_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn ts_prop_key(value: &str) -> String {
    if is_ts_identifier(value) {
        value.to_owned()
    } else {
        format!("\"{value}\"")
    }
}

fn is_ts_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
}

fn html_tag_type(tag: &str) -> String {
    if tag == "input" {
        return "ClayInputProps | ClaySwitchProps | ClayCheckboxProps | ClayRadioProps | ClaySliderProps | ClayNumberInputProps | ClaySlotOverrideProps".to_owned();
    }

    if HTML_CONTAINER_TAGS.contains(&tag) {
        return "ClayRowProps | ClayColumnProps | ClaySlotOverrideProps".to_owned();
    }

    if HTML_TEXT_TAGS.contains(&tag) {
        return "ClayLabelProps | ClaySlotOverrideProps".to_owned();
    }

    if let Some((_, family_name)) = HTML_EXPLICIT_FAMILY_TAGS
        .iter()
        .find(|(html_tag, _)| *html_tag == tag)
    {
        return format!(
            "{} | ClaySlotOverrideProps",
            family_props_type_name(family_name)
        );
    }

    "ClaySlotOverrideProps".to_owned()
}

fn event_handler_names(kind: EventKind) -> &'static [&'static str] {
    match kind {
        EventKind::Clicked => &["onClick"],
        EventKind::Changed => &["onChange", "onInput", "onChanged"],
        EventKind::Submitted => &["onSubmit", "onSubmitted"],
        EventKind::Selected => &["onSelect", "onSelected"],
        EventKind::Toggled => &["onToggle", "onToggled"],
        EventKind::Confirmed => &["onConfirm", "onConfirmed"],
        EventKind::Cancelled => &["onCancel", "onCancelled"],
        EventKind::Opened => &["onOpen", "onOpened"],
        EventKind::Closed => &["onClose", "onClosed"],
        EventKind::CommandInvoked => &["onCommand", "onCommandInvoked"],
    }
}

fn lowerer_aliases(prop_name: &str) -> &'static [&'static str] {
    match prop_name {
        "class" => &["className", "classNames"],
        "class_list" => &["classList"],
        "slot_classes" => &["slotClasses", "slotClassNames"],
        "node_id" => &["id", "nodeId"],
        "action_id" => &["actionId"],
        "selected_item_id" => &["selectedItemId"],
        "selected_item_ids" => &["selectedItemIds"],
        "item_id" => &["itemId"],
        "helper_text" => &["helperText"],
        "padding_x" => &["paddingX"],
        "padding_y" => &["paddingY"],
        "offset_x" => &["offsetX"],
        "offset_y" => &["offsetY"],
        "leading_icon" => &["leadingIcon"],
        "trailing_icon" => &["trailingIcon"],
        "trailing_text" => &["trailingText"],
        "icon_only" => &["iconOnly"],
        "confirm_label" => &["confirmLabel"],
        "cancel_label" => &["cancelLabel"],
        "confirm_action_id" => &["confirmActionId"],
        "cancel_action_id" => &["cancelActionId"],
        "max_height" => &["maxHeight"],
        "filter_placeholder" => &["filterPlaceholder"],
        "popup_width" => &["popupWidth"],
        "popup_max_height" => &["popupMaxHeight"],
        "current_page" => &["currentPage"],
        "page_count" => &["pageCount"],
        "sibling_count" => &["siblingCount"],
        "trigger_label" => &["triggerLabel"],
        "trigger_variant" => &["triggerVariant"],
        "delay_ms" => &["delayMs"],
        "side_offset" => &["sideOffset"],
        "region_width" => &["regionWidth"],
        "region_height" => &["regionHeight"],
        "left_title" => &["leftTitle"],
        "right_title" => &["rightTitle"],
        "row_height" => &["rowHeight"],
        "indent_width" => &["indentWidth"],
        "badge_fill" => &["badgeFill"],
        "playback_state" => &["playbackState"],
        "duration_seconds" => &["durationSeconds"],
        "play_pause_action_id" => &["playPauseActionId"],
        "image_width" => &["imageWidth"],
        "image_height" => &["imageHeight"],
        "image_frame" => &["imageFrame"],
        "icon_size" => &["iconSize"],
        "max_visible" => &["maxVisible"],
        "duration_secs" => &["durationSecs"],
        "corner_radius" => &["cornerRadius"],
        "source" => &["src"],
        "for" => &["htmlFor"],
        "value" => &["checked", "defaultChecked"],
        _ => &[],
    }
}

#[derive(Debug, Clone)]
struct TsProp {
    ty: String,
    optional: bool,
}

#[derive(Debug, Clone, Copy)]
enum EmitMode {
    SchemaRequired,
    AllOptional,
}

#[cfg(test)]
mod tests {
    use super::typescript_declarations;

    #[test]
    fn checked_in_typescript_declarations_are_current() {
        assert_eq!(
            typescript_declarations(),
            include_str!("../../types/contract.generated.d.ts")
        );
    }
}
