use crate::support;
use anyhow::{Context, Result};
use std::path::Path;

pub fn run(repo_root: &Path) -> Result<()> {
    let definitions = support::parse_catalog_definitions(repo_root)?;
    let docs_root = repo_root.join("docs/llm");
    let components_dir = docs_root.join("components");
    std::fs::create_dir_all(&components_dir)
        .with_context(|| format!("failed to create {}", components_dir.display()))?;

    let component_template = support::read(&docs_root.join("templates/component.md"))
        .context("missing docs/llm/templates/component.md")?;

    for definition in &definitions {
        let family = support::default_family(definition);
        let stub_path = support::component_stub_path(repo_root, &definition.id);
        if !stub_path.exists() {
            let stub = support::render_template(
                &component_template,
                &[
                    ("{{id}}", &definition.id),
                    ("{{label}}", &definition.label),
                    ("{{family}}", family),
                    ("{{summary}}", &support::default_summary(definition)),
                    ("{{family_template}}", &format!("family-{family}.md")),
                ],
            );
            support::write(&stub_path, &stub)?;
        }
    }

    let stubs = definitions
        .iter()
        .map(|definition| {
            support::parse_doc_stub(&support::component_stub_path(repo_root, &definition.id))
        })
        .collect::<Result<Vec<_>>>()?;

    verify_readme_links(repo_root)?;

    let mut contents = String::from(
        "# Components Reference\n\nGenerated by `cargo xtask sync-llm-docs`.\n\n| ID | Label | Group | Family | Summary |\n| --- | --- | --- | --- | --- |\n",
    );

    for (definition, stub) in definitions.iter().zip(stubs.iter()) {
        contents.push_str(&format!(
            "| `{}` | {} | {} | `{}` | {} |\n",
            definition.id,
            stub.label,
            definition.group.title(),
            stub.family,
            stub.summary
        ));
    }

    contents.push_str("\n## Component Stubs\n\n");
    for stub in &stubs {
        let relative = stub
            .path
            .strip_prefix(repo_root)
            .unwrap_or(stub.path.as_path())
            .display();
        contents.push_str(&format!(
            "### {}\n\n- ID: `{}`\n- Family: `{}`\n- Stub: `{}`\n- Summary: {}\n\n",
            stub.label, stub.id, stub.family, relative, stub.summary
        ));
    }

    let reference_path = docs_root.join("components-reference.md");
    support::write_if_changed(&reference_path, &contents)?;
    Ok(())
}

fn verify_readme_links(repo_root: &Path) -> Result<()> {
    support::require_file(&repo_root.join("docs/llm/README.md"))?;
    support::require_file(&repo_root.join("docs/llm/architecture-overview.md"))?;
    support::require_file(&repo_root.join("docs/llm/authoring-rules.md"))?;
    Ok(())
}
