// @generated by `cargo run -p clay-jsx-runtime --bin generate-contract-types`
// Do not edit by hand.

/* eslint-disable */

type ClayContractModelVersion = 2;
type ClayContractSchemaFingerprint = "2dd3d456ca6dd235f87a26b00779c5d49f922aae5e839d2fc2e3525cebf591f1";

type ClayContractFamily =
  | "row"
  | "column"
  | "inset"
  | "sized-box"
  | "spacer"
  | "card"
  | "sidebar"
  | "toolbar"
  | "menu-bar"
  | "tabs"
  | "label"
  | "button"
  | "button-group"
  | "input"
  | "number-input"
  | "checkbox"
  | "switch"
  | "select"
  | "field"
  | "separator"
  | "collapsible"
  | "dialogue-modal"
  | "hierarchy"
  | "spinner"
  | "progress"
  | "toast-viewport"
  | "color"
  | "icon"
  | "image"
  | "twemoji"
  | "kbd"
  | "skeleton"
  | "slider"
  | "radio"
  | "radio-group"
  | "combobox"
  | "emoji-selector"
  | "pagination"
  | "tooltip"
  | "popover"
  | "dropdown-menu"
  | "context-menu"
  | "open-with"
  | "collab-cursor"
  | "icon-toolbar"
  | "file-tree"
  | "drag-board"
  | "audio-playback"
  | "image-tile"
  | "command"
;

type ClayNode = import("react").ReactNode;
type ClayRecord = Readonly<Record<string, unknown>>;

interface ClayNodeCommon {
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id: string;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
}

interface ClayActions {
  readonly cancel?: string;
  readonly change?: string;
  readonly click?: string;
  readonly close?: string;
  readonly confirm?: string;
  readonly open?: string;
  readonly select?: string;
  readonly submit?: string;
}

interface ClayLayout {
  readonly align?: ClayAlign;
  readonly basis?: ClayLayoutLength;
  readonly colSpan?: number;
  readonly col_span?: number;
  readonly columns?: readonly ClayLayoutTrack[];
  readonly direction?: ClayLayoutDirection;
  readonly display?: ClayLayoutDisplay;
  readonly gapX?: number;
  readonly gapY?: number;
  readonly gap_x?: number;
  readonly gap_y?: number;
  readonly grow?: number;
  readonly height?: ClayLayoutLength;
  readonly justify?: ClayJustify;
  readonly margin?: ClayLayoutEdges;
  readonly maxHeight?: ClayLayoutLength;
  readonly maxWidth?: ClayLayoutLength;
  readonly max_height?: ClayLayoutLength;
  readonly max_width?: ClayLayoutLength;
  readonly minHeight?: ClayLayoutLength;
  readonly minWidth?: ClayLayoutLength;
  readonly min_height?: ClayLayoutLength;
  readonly min_width?: ClayLayoutLength;
  readonly overflowX?: ClayLayoutOverflow;
  readonly overflowY?: ClayLayoutOverflow;
  readonly overflow_x?: ClayLayoutOverflow;
  readonly overflow_y?: ClayLayoutOverflow;
  readonly padding?: ClayLayoutEdges;
  readonly rowSpan?: number;
  readonly row_span?: number;
  readonly rows?: readonly ClayLayoutTrack[];
  readonly shrink?: number;
  readonly width?: ClayLayoutLength;
  readonly wrap?: boolean;
}

interface ClayLayoutEdges {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
}

interface ClayLayoutLength {
  readonly kind: ClayLayoutLengthKind;
  readonly value?: number;
}

type ClayLayoutLengthKind =
  | "auto"
  | "px"
  | "percent"
;

interface ClayLayoutTrack {
  readonly kind: ClayLayoutTrackKind;
  readonly value?: number;
}

type ClayLayoutTrackKind =
  | "auto"
  | "fr"
  | "px"
  | "percent"
;

type ClayLayoutDisplay =
  | "flow"
  | "flex"
  | "grid"
  | "overlay"
;

type ClayLayoutDirection =
  | "row"
  | "column"
;

type ClayLayoutOverflow =
  | "visible"
  | "hidden"
  | "scroll"
;

type ClayJustify =
  | "start"
  | "center"
  | "end"
;

type ClayAlign =
  | "start"
  | "center"
  | "end"
  | "stretch"
;

type ClayToolbarAnchor =
  | "top_left"
  | "top_center"
  | "top_right"
  | "left_center"
  | "center"
  | "right_center"
  | "bottom_left"
  | "bottom_center"
  | "bottom_right"
;

type ClayTabsStyle =
  | "underline"
  | "segmented"
  | "blender_topbar"
  | "stacked"
  | "rail"
;

type ClayButtonVariant =
  | "primary"
  | "secondary"
  | "ghost"
  | "link"
;

type ClayControlSize =
  | "sm"
  | "md"
;

type ClayLabelTone =
  | "primary"
  | "secondary"
  | "muted"
  | "destructive"
;

type ClayLabelWeight =
  | "regular"
  | "semibold"
  | "bold"
;

type ClaySelectVariant =
  | "default"
  | "secondary"
;

type ClaySidebarSide =
  | "left"
  | "right"
;

type ClayDialogueIntent =
  | "default"
  | "alert"
;

type ClayToastIntent =
  | "neutral"
  | "success"
  | "destructive"
;

type ClayToastPlacement =
  | "top_left"
  | "top_center"
  | "top_right"
  | "center_left"
  | "center"
  | "center_right"
  | "bottom_left"
  | "bottom_center"
  | "bottom_right"
;

type ClayNumberInputAxis =
  | "horizontal"
  | "vertical"
;

type ClayHierarchyItemKind =
  | "folder"
  | "frame"
  | "group"
  | "player"
  | "weapon"
  | "clothing"
  | "hitbox"
  | "vector"
;

type ClayMenuEntryKind =
  | "action"
  | "separator"
;

type ClayHierarchyIconStyle =
  | "emoji"
  | "icons"
;

type ClayHierarchyStyle =
  | "normal"
  | "component"
;

interface ClayActionItem {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly itemId?: string;
  readonly item_id: string;
  readonly label: string;
}

interface ClayChoiceItem {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly itemId?: string;
  readonly item_id: string;
  readonly label: string;
}

interface ClayTabItem {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly icon?: string;
  readonly iconOnly?: boolean;
  readonly icon_only?: boolean;
  readonly itemId?: string;
  readonly item_id: string;
  readonly label: string;
}

interface ClayMenuAction {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly itemId?: string;
  readonly item_id: string;
  readonly label: string;
  readonly leadingIcon?: string;
  readonly leading_icon?: string;
  readonly shortcut?: string;
}

interface ClayMenuEntry {
  readonly action?: ClayMenuAction;
  readonly kind: ClayMenuEntryKind;
}

interface ClayMenu {
  readonly entries: readonly ClayMenuEntry[];
  readonly label: string;
  readonly menuId?: string;
  readonly menu_id: string;
  readonly width?: number;
}

interface ClayHierarchyItem {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly children?: readonly ClayHierarchyItem[];
  readonly itemId?: string;
  readonly item_id: string;
  readonly kind: ClayHierarchyItemKind;
  readonly label: string;
  readonly locked?: boolean;
  readonly open?: boolean;
}

interface ClayToastItem {
  readonly actionId?: string;
  readonly action_id?: string;
  readonly description?: string;
  readonly durationSecs?: number;
  readonly duration_secs?: number;
  readonly intent?: ClayToastIntent;
  readonly itemId?: string;
  readonly item_id: string;
  readonly title: string;
}

type ClayEventKind =
  | "clicked"
  | "changed"
  | "submitted"
  | "selected"
  | "toggled"
  | "confirmed"
  | "cancelled"
  | "opened"
  | "closed"
  | "command_invoked";

interface ClayEvent {
  readonly kind?: ClayEventKind;
  readonly value?: unknown;
  readonly metadata?: Readonly<Record<string, unknown>>;
  readonly node_id?: string;
  readonly action_id?: string;
  readonly [key: string]: unknown;
}

type ClayEventHandler<TValue = unknown> = (event: ClayEvent, value?: TValue) => void;

interface ClayMotionValues {
  readonly opacity?: number;
  readonly x?: number;
  readonly y?: number;
  readonly scale?: number;
  readonly scaleX?: number;
  readonly scaleY?: number;
  readonly rotate?: number;
  readonly width?: number;
  readonly height?: number;
  readonly gap?: number;
  readonly paddingX?: number;
  readonly paddingY?: number;
  readonly cornerRadius?: number;
}

interface ClayMotionTransition {
  readonly type?: "tween";
  readonly duration?: number;
  readonly delay?: number;
  readonly ease?: "linear" | "easeIn" | "easeOut" | "easeInOut";
}

interface ClayMotionAuthoringProps {
  readonly initial?: ClayMotionValues;
  readonly animate?: ClayMotionValues;
  readonly transition?: ClayMotionTransition;
  readonly exit?: ClayMotionValues;
  readonly whileHover?: ClayMotionValues;
  readonly whileTap?: ClayMotionValues;
  readonly whileFocus?: ClayMotionValues;
  readonly whileInView?: ClayMotionValues;
}

type ClayIdentityNodeId = { readonly id: string } | { readonly nodeId: string } | { readonly node_id: string };

interface ClayRowPropsBase {
  readonly "data-slot"?: "row";
  readonly dataSlot?: "row";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly align?: ClayAlign;
  readonly children?: readonly ClayNode[];
  readonly gap?: number;
  readonly justify?: ClayJustify;
  readonly onEvent?: ClayEventHandler;
}
type ClayRowProps = ClayRowPropsBase;

interface ClayColumnPropsBase {
  readonly "data-slot"?: "column";
  readonly dataSlot?: "column";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly align?: ClayAlign;
  readonly children?: readonly ClayNode[];
  readonly gap?: number;
  readonly justify?: ClayJustify;
  readonly onEvent?: ClayEventHandler;
}
type ClayColumnProps = ClayColumnPropsBase;

interface ClayInsetPropsBase {
  readonly "data-slot"?: "inset";
  readonly dataSlot?: "inset";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly children?: readonly ClayNode[];
  readonly paddingX?: number;
  readonly paddingY?: number;
  readonly padding_x?: number;
  readonly padding_y?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClayInsetProps = ClayInsetPropsBase;

interface ClaySizedBoxPropsBase {
  readonly "data-slot"?: "sized-box";
  readonly dataSlot?: "sized-box";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly children?: readonly ClayNode[];
  readonly height?: number;
  readonly width?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClaySizedBoxProps = ClaySizedBoxPropsBase;

interface ClaySpacerPropsBase {
  readonly "data-slot"?: "spacer";
  readonly dataSlot?: "spacer";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly flex?: boolean;
  readonly height?: number;
  readonly width?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClaySpacerProps = ClaySpacerPropsBase;

interface ClayCardPropsBase {
  readonly "data-slot"?: "card";
  readonly dataSlot?: "card";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly children?: readonly ClayNode[];
  readonly paddingX?: number;
  readonly paddingY?: number;
  readonly padding_x?: number;
  readonly padding_y?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClayCardProps = ClayCardPropsBase;

interface ClaySidebarPropsBase {
  readonly "data-slot"?: "sidebar";
  readonly dataSlot?: "sidebar";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly children?: readonly ClayNode[];
  readonly open?: boolean;
  readonly side?: ClaySidebarSide;
  readonly title?: string;
  readonly width?: number;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClaySidebarProps = ClaySidebarPropsBase & ClayIdentityNodeId;

interface ClayToolbarPropsBase {
  readonly "data-slot"?: "toolbar";
  readonly dataSlot?: "toolbar";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly anchor?: ClayToolbarAnchor;
  readonly children?: readonly ClayNode[];
  readonly offsetX?: number;
  readonly offsetY?: number;
  readonly offset_x?: number;
  readonly offset_y?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClayToolbarProps = ClayToolbarPropsBase;

interface ClayMenuBarPropsBase {
  readonly "data-slot"?: "menu-bar";
  readonly dataSlot?: "menu-bar";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly menus?: readonly ClayMenu[];
  readonly onCommand?: ClayEventHandler;
  readonly onCommandInvoked?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayMenuBarProps = ClayMenuBarPropsBase & ClayIdentityNodeId;

interface ClayTabsPropsBase {
  readonly "data-slot"?: "tabs";
  readonly dataSlot?: "tabs";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly items?: readonly ClayTabItem[];
  readonly selectedItemId?: string;
  readonly selected_item_id?: string;
  readonly style?: ClayTabsStyle;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayTabsProps = ClayTabsPropsBase & ClayIdentityNodeId;

interface ClayLabelPropsBase {
  readonly "data-slot"?: "label";
  readonly dataSlot?: "label";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly size?: number;
  readonly text?: string;
  readonly tone?: ClayLabelTone;
  readonly weight?: ClayLabelWeight;
  readonly onEvent?: ClayEventHandler;
}
type ClayLabelProps = ClayLabelPropsBase;

interface ClayButtonPropsBase {
  readonly "data-slot"?: "button";
  readonly dataSlot?: "button";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly iconOnly?: boolean;
  readonly icon_only?: boolean;
  readonly label?: string;
  readonly leadingIcon?: string;
  readonly leading_icon?: string;
  readonly selected?: boolean;
  readonly size?: ClayControlSize;
  readonly trailingIcon?: string;
  readonly trailingText?: string;
  readonly trailing_icon?: string;
  readonly trailing_text?: string;
  readonly variant?: ClayButtonVariant;
  readonly onClick?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayButtonProps = ClayButtonPropsBase;

interface ClayButtonGroupPropsBase {
  readonly "data-slot"?: "button-group";
  readonly dataSlot?: "button-group";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly items?: readonly ClayActionItem[];
  readonly onCommand?: ClayEventHandler;
  readonly onCommandInvoked?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayButtonGroupProps = ClayButtonGroupPropsBase;

interface ClayInputPropsBase {
  readonly "data-slot"?: "input";
  readonly dataSlot?: "input";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly checked?: string;
  readonly defaultChecked?: string;
  readonly leadingIcon?: string;
  readonly leading_icon?: string;
  readonly placeholder?: string;
  readonly value?: string;
  readonly width?: number;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
  readonly onSubmit?: ClayEventHandler;
  readonly onSubmitted?: ClayEventHandler;
}
type ClayInputProps = ClayInputPropsBase & ClayIdentityNodeId;

interface ClayNumberInputPropsBase {
  readonly "data-slot"?: "number-input";
  readonly dataSlot?: "number-input";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly axis?: ClayNumberInputAxis;
  readonly checked?: number;
  readonly decimals?: number;
  readonly defaultChecked?: number;
  readonly max?: number;
  readonly min?: number;
  readonly prefix?: string;
  readonly speed?: number;
  readonly suffix?: string;
  readonly value?: number;
  readonly width?: number;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
}
type ClayNumberInputProps = ClayNumberInputPropsBase & ClayIdentityNodeId;

interface ClayCheckboxPropsBase {
  readonly "data-slot"?: "checkbox";
  readonly dataSlot?: "checkbox";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly checked?: boolean;
  readonly defaultChecked?: boolean;
  readonly label?: string;
  readonly value?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClayCheckboxProps = ClayCheckboxPropsBase & ClayIdentityNodeId;

interface ClaySwitchPropsBase {
  readonly "data-slot"?: "switch";
  readonly dataSlot?: "switch";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly checked?: boolean;
  readonly defaultChecked?: boolean;
  readonly label?: string;
  readonly size?: ClayControlSize;
  readonly value?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClaySwitchProps = ClaySwitchPropsBase & ClayIdentityNodeId;

interface ClaySelectPropsBase {
  readonly "data-slot"?: "select";
  readonly dataSlot?: "select";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly items?: readonly ClayChoiceItem[];
  readonly leadingIcon?: string;
  readonly leading_icon?: string;
  readonly placeholder?: string;
  readonly selectedItemId?: string;
  readonly selected_item_id?: string;
  readonly variant?: ClaySelectVariant;
  readonly width?: number;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClaySelectProps = ClaySelectPropsBase & ClayIdentityNodeId;

interface ClayFieldPropsBase {
  readonly "data-slot"?: "field";
  readonly dataSlot?: "field";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly checked?: string;
  readonly defaultChecked?: string;
  readonly helperText?: string;
  readonly helper_text?: string;
  readonly label?: string;
  readonly placeholder?: string;
  readonly value?: string;
  readonly width?: number;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
}
type ClayFieldProps = ClayFieldPropsBase & ClayIdentityNodeId;

interface ClaySeparatorPropsBase {
  readonly "data-slot"?: "separator";
  readonly dataSlot?: "separator";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClaySeparatorProps = ClaySeparatorPropsBase;

interface ClayCollapsiblePropsBase {
  readonly "data-slot"?: "collapsible";
  readonly dataSlot?: "collapsible";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly children?: readonly ClayNode[];
  readonly leadingIcon?: string;
  readonly leading_icon?: string;
  readonly open?: boolean;
  readonly title?: string;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onOpen?: ClayEventHandler;
  readonly onOpened?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClayCollapsibleProps = ClayCollapsiblePropsBase & ClayIdentityNodeId;

interface ClayDialogueModalPropsBase {
  readonly "data-slot"?: "dialogue-modal";
  readonly dataSlot?: "dialogue-modal";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly cancelActionId?: string;
  readonly cancelLabel?: string;
  readonly cancel_action_id?: string;
  readonly cancel_label?: string;
  readonly children?: readonly ClayNode[];
  readonly confirmActionId?: string;
  readonly confirmLabel?: string;
  readonly confirm_action_id?: string;
  readonly confirm_label?: string;
  readonly description?: string;
  readonly intent?: ClayDialogueIntent;
  readonly open?: boolean;
  readonly title?: string;
  readonly width?: number;
  readonly onCancel?: ClayEventHandler;
  readonly onCancelled?: ClayEventHandler;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onConfirm?: ClayEventHandler;
  readonly onConfirmed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayDialogueModalProps = ClayDialogueModalPropsBase & ClayIdentityNodeId;

interface ClayHierarchyPropsBase {
  readonly "data-slot"?: "hierarchy";
  readonly dataSlot?: "hierarchy";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly actionId?: string;
  readonly action_id?: string;
  readonly iconStyle?: ClayHierarchyIconStyle;
  readonly icon_style?: ClayHierarchyIconStyle;
  readonly indentWidth?: number;
  readonly indent_width?: number;
  readonly items?: readonly ClayHierarchyItem[];
  readonly rowHeight?: number;
  readonly row_height?: number;
  readonly selectedItemId?: string;
  readonly selected_item_id?: string;
  readonly style?: ClayHierarchyStyle;
  readonly width?: number;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onOpen?: ClayEventHandler;
  readonly onOpened?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayHierarchyProps = ClayHierarchyPropsBase & ClayIdentityNodeId;

interface ClaySpinnerPropsBase {
  readonly "data-slot"?: "spinner";
  readonly dataSlot?: "spinner";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly size?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClaySpinnerProps = ClaySpinnerPropsBase;

interface ClayProgressPropsBase {
  readonly "data-slot"?: "progress";
  readonly dataSlot?: "progress";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly checked?: number;
  readonly defaultChecked?: number;
  readonly height?: number;
  readonly value?: number;
  readonly width?: number;
  readonly onEvent?: ClayEventHandler;
}
type ClayProgressProps = ClayProgressPropsBase;

interface ClayToastViewportPropsBase {
  readonly "data-slot"?: "toast-viewport";
  readonly dataSlot?: "toast-viewport";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly gap?: number;
  readonly marginX?: number;
  readonly marginY?: number;
  readonly margin_x?: number;
  readonly margin_y?: number;
  readonly maxVisible?: number;
  readonly max_visible?: number;
  readonly overlap?: number;
  readonly placement?: ClayToastPlacement;
  readonly toasts?: readonly ClayToastItem[];
  readonly width?: number;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onOpen?: ClayEventHandler;
  readonly onOpened?: ClayEventHandler;
}
type ClayToastViewportProps = ClayToastViewportPropsBase & ClayIdentityNodeId;

interface ClayColorPropsBase {
  readonly "data-slot"?: "color";
  readonly dataSlot?: "color";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayColorProps = ClayColorPropsBase;

interface ClayIconPropsBase {
  readonly "data-slot"?: "icon";
  readonly dataSlot?: "icon";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayIconProps = ClayIconPropsBase;

interface ClayImagePropsBase {
  readonly "data-slot"?: "image";
  readonly dataSlot?: "image";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayImageProps = ClayImagePropsBase;

interface ClayTwemojiPropsBase {
  readonly "data-slot"?: "twemoji";
  readonly dataSlot?: "twemoji";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayTwemojiProps = ClayTwemojiPropsBase;

interface ClayKbdPropsBase {
  readonly "data-slot"?: "kbd";
  readonly dataSlot?: "kbd";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayKbdProps = ClayKbdPropsBase;

interface ClaySkeletonPropsBase {
  readonly "data-slot"?: "skeleton";
  readonly dataSlot?: "skeleton";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClaySkeletonProps = ClaySkeletonPropsBase;

interface ClaySliderPropsBase {
  readonly "data-slot"?: "slider";
  readonly dataSlot?: "slider";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
}
type ClaySliderProps = ClaySliderPropsBase & ClayIdentityNodeId;

interface ClayRadioPropsBase {
  readonly "data-slot"?: "radio";
  readonly dataSlot?: "radio";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClayRadioProps = ClayRadioPropsBase & ClayIdentityNodeId;

interface ClayRadioGroupPropsBase {
  readonly "data-slot"?: "radio-group";
  readonly dataSlot?: "radio-group";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayRadioGroupProps = ClayRadioGroupPropsBase & ClayIdentityNodeId;

interface ClayComboboxPropsBase {
  readonly "data-slot"?: "combobox";
  readonly dataSlot?: "combobox";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayComboboxProps = ClayComboboxPropsBase & ClayIdentityNodeId;

interface ClayEmojiSelectorPropsBase {
  readonly "data-slot"?: "emoji-selector";
  readonly dataSlot?: "emoji-selector";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayEmojiSelectorProps = ClayEmojiSelectorPropsBase & ClayIdentityNodeId;

interface ClayPaginationPropsBase {
  readonly "data-slot"?: "pagination";
  readonly dataSlot?: "pagination";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayPaginationProps = ClayPaginationPropsBase;

interface ClayTooltipPropsBase {
  readonly "data-slot"?: "tooltip";
  readonly dataSlot?: "tooltip";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayTooltipProps = ClayTooltipPropsBase;

interface ClayPopoverPropsBase {
  readonly "data-slot"?: "popover";
  readonly dataSlot?: "popover";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onOpen?: ClayEventHandler;
  readonly onOpened?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClayPopoverProps = ClayPopoverPropsBase & ClayIdentityNodeId;

interface ClayDropdownMenuPropsBase {
  readonly "data-slot"?: "dropdown-menu";
  readonly dataSlot?: "dropdown-menu";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onCommand?: ClayEventHandler;
  readonly onCommandInvoked?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayDropdownMenuProps = ClayDropdownMenuPropsBase & ClayIdentityNodeId;

interface ClayContextMenuPropsBase {
  readonly "data-slot"?: "context-menu";
  readonly dataSlot?: "context-menu";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onCommand?: ClayEventHandler;
  readonly onCommandInvoked?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayContextMenuProps = ClayContextMenuPropsBase & ClayIdentityNodeId;

interface ClayOpenWithPropsBase {
  readonly "data-slot"?: "open-with";
  readonly dataSlot?: "open-with";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onCommand?: ClayEventHandler;
  readonly onCommandInvoked?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayOpenWithProps = ClayOpenWithPropsBase & ClayIdentityNodeId;

interface ClayCollabCursorPropsBase {
  readonly "data-slot"?: "collab-cursor";
  readonly dataSlot?: "collab-cursor";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
}
type ClayCollabCursorProps = ClayCollabCursorPropsBase;

interface ClayIconToolbarPropsBase {
  readonly "data-slot"?: "icon-toolbar";
  readonly dataSlot?: "icon-toolbar";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayIconToolbarProps = ClayIconToolbarPropsBase;

interface ClayFileTreePropsBase {
  readonly "data-slot"?: "file-tree";
  readonly dataSlot?: "file-tree";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onClose?: ClayEventHandler;
  readonly onClosed?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onOpen?: ClayEventHandler;
  readonly onOpened?: ClayEventHandler;
  readonly onSelect?: ClayEventHandler;
  readonly onSelected?: ClayEventHandler;
}
type ClayFileTreeProps = ClayFileTreePropsBase & ClayIdentityNodeId;

interface ClayDragBoardPropsBase {
  readonly "data-slot"?: "drag-board";
  readonly dataSlot?: "drag-board";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
}
type ClayDragBoardProps = ClayDragBoardPropsBase & ClayIdentityNodeId;

interface ClayAudioPlaybackPropsBase {
  readonly "data-slot"?: "audio-playback";
  readonly dataSlot?: "audio-playback";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onEvent?: ClayEventHandler;
  readonly onToggle?: ClayEventHandler;
  readonly onToggled?: ClayEventHandler;
}
type ClayAudioPlaybackProps = ClayAudioPlaybackPropsBase;

interface ClayImageTilePropsBase {
  readonly "data-slot"?: "image-tile";
  readonly dataSlot?: "image-tile";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onClick?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
}
type ClayImageTileProps = ClayImageTilePropsBase;

interface ClayCommandPropsBase {
  readonly "data-slot"?: "command";
  readonly dataSlot?: "command";
  readonly role?: string;
  readonly type?: string;
  readonly actions?: ClayActions;
  readonly class?: string;
  readonly classList?: readonly string[];
  readonly className?: string;
  readonly classNames?: string;
  readonly class_list?: readonly string[];
  readonly enabled?: boolean;
  readonly id?: string;
  readonly layout?: ClayLayout;
  readonly nodeId?: string;
  readonly node_id?: string;
  readonly slotClassNames?: Readonly<Record<string, string>>;
  readonly slotClasses?: Readonly<Record<string, string>>;
  readonly slot_classes?: Readonly<Record<string, string>>;
  readonly visible?: boolean;
  readonly onChange?: ClayEventHandler;
  readonly onChanged?: ClayEventHandler;
  readonly onEvent?: ClayEventHandler;
  readonly onInput?: ClayEventHandler;
}
type ClayCommandProps = ClayCommandPropsBase & ClayIdentityNodeId;

interface ClayFamilyPropsMap {
  readonly "row": ClayRowProps;
  readonly "column": ClayColumnProps;
  readonly "inset": ClayInsetProps;
  readonly "sized-box": ClaySizedBoxProps;
  readonly "spacer": ClaySpacerProps;
  readonly "card": ClayCardProps;
  readonly "sidebar": ClaySidebarProps;
  readonly "toolbar": ClayToolbarProps;
  readonly "menu-bar": ClayMenuBarProps;
  readonly "tabs": ClayTabsProps;
  readonly "label": ClayLabelProps;
  readonly "button": ClayButtonProps;
  readonly "button-group": ClayButtonGroupProps;
  readonly "input": ClayInputProps;
  readonly "number-input": ClayNumberInputProps;
  readonly "checkbox": ClayCheckboxProps;
  readonly "switch": ClaySwitchProps;
  readonly "select": ClaySelectProps;
  readonly "field": ClayFieldProps;
  readonly "separator": ClaySeparatorProps;
  readonly "collapsible": ClayCollapsibleProps;
  readonly "dialogue-modal": ClayDialogueModalProps;
  readonly "hierarchy": ClayHierarchyProps;
  readonly "spinner": ClaySpinnerProps;
  readonly "progress": ClayProgressProps;
  readonly "toast-viewport": ClayToastViewportProps;
  readonly "color": ClayColorProps;
  readonly "icon": ClayIconProps;
  readonly "image": ClayImageProps;
  readonly "twemoji": ClayTwemojiProps;
  readonly "kbd": ClayKbdProps;
  readonly "skeleton": ClaySkeletonProps;
  readonly "slider": ClaySliderProps;
  readonly "radio": ClayRadioProps;
  readonly "radio-group": ClayRadioGroupProps;
  readonly "combobox": ClayComboboxProps;
  readonly "emoji-selector": ClayEmojiSelectorProps;
  readonly "pagination": ClayPaginationProps;
  readonly "tooltip": ClayTooltipProps;
  readonly "popover": ClayPopoverProps;
  readonly "dropdown-menu": ClayDropdownMenuProps;
  readonly "context-menu": ClayContextMenuProps;
  readonly "open-with": ClayOpenWithProps;
  readonly "collab-cursor": ClayCollabCursorProps;
  readonly "icon-toolbar": ClayIconToolbarProps;
  readonly "file-tree": ClayFileTreeProps;
  readonly "drag-board": ClayDragBoardProps;
  readonly "audio-playback": ClayAudioPlaybackProps;
  readonly "image-tile": ClayImageTileProps;
  readonly "command": ClayCommandProps;
}

type ClayAnyFamilyProps = ClayFamilyPropsMap[ClayContractFamily];

type ClaySlotOverrideProps = { readonly "data-slot": ClayContractFamily } & ClayAnyFamilyProps;

interface ClayIntrinsicElements {
  readonly "row": ClayRowProps;
  readonly "column": ClayColumnProps;
  readonly "inset": ClayInsetProps;
  readonly "sized-box": ClaySizedBoxProps;
  readonly "spacer": ClaySpacerProps;
  readonly "card": ClayCardProps;
  readonly "sidebar": ClaySidebarProps;
  readonly "toolbar": ClayToolbarProps;
  readonly "menu-bar": ClayMenuBarProps;
  readonly "tabs": ClayTabsProps;
  readonly "button-group": ClayButtonGroupProps;
  readonly "number-input": ClayNumberInputProps;
  readonly "checkbox": ClayCheckboxProps;
  readonly "switch": ClaySwitchProps;
  readonly "select": ClaySelectProps;
  readonly "field": ClayFieldProps;
  readonly "separator": ClaySeparatorProps;
  readonly "collapsible": ClayCollapsibleProps;
  readonly "dialogue-modal": ClayDialogueModalProps;
  readonly "hierarchy": ClayHierarchyProps;
  readonly "spinner": ClaySpinnerProps;
  readonly "toast-viewport": ClayToastViewportProps;
  readonly "color": ClayColorProps;
  readonly "icon": ClayIconProps;
  readonly "image": ClayImageProps;
  readonly "twemoji": ClayTwemojiProps;
  readonly "skeleton": ClaySkeletonProps;
  readonly "slider": ClaySliderProps;
  readonly "radio": ClayRadioProps;
  readonly "radio-group": ClayRadioGroupProps;
  readonly "combobox": ClayComboboxProps;
  readonly "emoji-selector": ClayEmojiSelectorProps;
  readonly "pagination": ClayPaginationProps;
  readonly "tooltip": ClayTooltipProps;
  readonly "popover": ClayPopoverProps;
  readonly "dropdown-menu": ClayDropdownMenuProps;
  readonly "context-menu": ClayContextMenuProps;
  readonly "open-with": ClayOpenWithProps;
  readonly "collab-cursor": ClayCollabCursorProps;
  readonly "icon-toolbar": ClayIconToolbarProps;
  readonly "file-tree": ClayFileTreeProps;
  readonly "drag-board": ClayDragBoardProps;
  readonly "audio-playback": ClayAudioPlaybackProps;
  readonly "image-tile": ClayImageTileProps;
  readonly "command": ClayCommandProps;
  readonly "box": ClaySizedBoxProps;
  readonly "sizedbox": ClaySizedBoxProps;
  readonly "dialogue": ClayDialogueModalProps;
  readonly "dialogueModal": ClayDialogueModalProps;
  readonly "dropdown": ClayDropdownMenuProps;
  readonly "dropdownMenu": ClayDropdownMenuProps;
  readonly "filetree": ClayFileTreeProps;
  readonly "imageTile": ClayImageTileProps;
  readonly "iconToolbar": ClayIconToolbarProps;
  readonly "radioGroup": ClayRadioGroupProps;
  readonly "toast": ClayToastViewportProps;
  readonly "img": ClayImageProps;
  readonly "section": ClayColumnProps;
  readonly "main": ClayColumnProps;
  readonly "header": ClayColumnProps;
  readonly "footer": ClayColumnProps;
  readonly "nav": ClayColumnProps;
  readonly "article": ClayColumnProps;
  readonly "a": ClayLabelProps | ClaySlotOverrideProps;
  readonly "aside": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
  readonly "button": ClayButtonProps | ClaySlotOverrideProps;
  readonly "code": ClayLabelProps | ClaySlotOverrideProps;
  readonly "dialog": ClayDialogueModalProps | ClaySlotOverrideProps;
  readonly "div": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
  readonly "em": ClayLabelProps | ClaySlotOverrideProps;
  readonly "form": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
  readonly "h1": ClayLabelProps | ClaySlotOverrideProps;
  readonly "h2": ClayLabelProps | ClaySlotOverrideProps;
  readonly "h3": ClayLabelProps | ClaySlotOverrideProps;
  readonly "h4": ClayLabelProps | ClaySlotOverrideProps;
  readonly "h5": ClayLabelProps | ClaySlotOverrideProps;
  readonly "h6": ClayLabelProps | ClaySlotOverrideProps;
  readonly "hr": ClaySeparatorProps | ClaySlotOverrideProps;
  readonly "input": ClayInputProps | ClaySwitchProps | ClayCheckboxProps | ClayRadioProps | ClaySliderProps | ClayNumberInputProps | ClaySlotOverrideProps;
  readonly "kbd": ClayKbdProps | ClaySlotOverrideProps;
  readonly "label": ClaySlotOverrideProps;
  readonly "li": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
  readonly "ol": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
  readonly "p": ClayLabelProps | ClaySlotOverrideProps;
  readonly "pre": ClayLabelProps | ClaySlotOverrideProps;
  readonly "progress": ClayProgressProps | ClaySlotOverrideProps;
  readonly "small": ClayLabelProps | ClaySlotOverrideProps;
  readonly "span": ClayLabelProps | ClaySlotOverrideProps;
  readonly "strong": ClayLabelProps | ClaySlotOverrideProps;
  readonly "ul": ClayRowProps | ClayColumnProps | ClaySlotOverrideProps;
}

declare module "egui/jsx-runtime" {
  import type { ReactElement } from "react";
  export const Fragment: unique symbol;
  export function jsx(type: unknown, props: unknown, key?: string | number): ReactElement;
  export function jsxs(type: unknown, props: unknown, key?: string | number): ReactElement;
  export function jsxDEV(
    type: unknown,
    props: unknown,
    key: string | number | undefined,
    isStaticChildren: boolean,
    source: unknown,
    self: unknown,
  ): ReactElement;

  export namespace JSX {
    type Element = ReactElement;
    interface ElementChildrenAttribute {
      readonly children: unknown;
    }
    interface IntrinsicAttributes {
      readonly key?: string | number;
    }
    interface IntrinsicElements extends ClayIntrinsicElements {}
  }
}

declare module "clay/jsx-runtime" {
  export * from "egui/jsx-runtime";
}

declare module "egui/jsx-dev-runtime" {
  export { Fragment, jsxDEV } from "egui/jsx-runtime";
}

declare module "clay/jsx-dev-runtime" {
  export * from "egui/jsx-dev-runtime";
}

declare module "egui" {
  import type * as React from "react";
  export type ContractFamily = ClayContractFamily;
  export type ContractModelVersion = ClayContractModelVersion;
  export type ContractSchemaFingerprint = ClayContractSchemaFingerprint;
  export type Event = ClayEvent;
  export const createContext: typeof React.createContext;
  export const startTransition: typeof React.startTransition;
  export const useContext: typeof React.useContext;
  export const useDeferredValue: typeof React.useDeferredValue;
  export const useEffect: typeof React.useEffect;
  export const useReducer: typeof React.useReducer;
  export const useRef: typeof React.useRef;
  export const useState: typeof React.useState;
  export const useSyncExternalStore: typeof React.useSyncExternalStore;
  export function render(node: React.ReactNode): void;
  export function requestRepaint(): void;
  export function eventValue<TValue = unknown>(event: unknown): TValue | undefined;
  export function log(level: string, message: string): void;
}

declare module "clay" {
  export * from "egui";
}

declare module "motion/react" {
  import type { ReactElement, ReactNode } from "react";
  type MotionComponent<TProps> = (props: TProps & ClayMotionAuthoringProps) => ReactElement | null;
  type MotionByFamily = {
    readonly "row": MotionComponent<ClayRowProps>;
    readonly "column": MotionComponent<ClayColumnProps>;
    readonly "inset": MotionComponent<ClayInsetProps>;
    readonly "sized-box": MotionComponent<ClaySizedBoxProps>;
    readonly "spacer": MotionComponent<ClaySpacerProps>;
    readonly "card": MotionComponent<ClayCardProps>;
    readonly "sidebar": MotionComponent<ClaySidebarProps>;
    readonly "toolbar": MotionComponent<ClayToolbarProps>;
    readonly "menu-bar": MotionComponent<ClayMenuBarProps>;
    readonly "tabs": MotionComponent<ClayTabsProps>;
    readonly "label": MotionComponent<ClayLabelProps>;
    readonly "button": MotionComponent<ClayButtonProps>;
    readonly "button-group": MotionComponent<ClayButtonGroupProps>;
    readonly "input": MotionComponent<ClayInputProps>;
    readonly "number-input": MotionComponent<ClayNumberInputProps>;
    readonly "checkbox": MotionComponent<ClayCheckboxProps>;
    readonly "switch": MotionComponent<ClaySwitchProps>;
    readonly "select": MotionComponent<ClaySelectProps>;
    readonly "field": MotionComponent<ClayFieldProps>;
    readonly "separator": MotionComponent<ClaySeparatorProps>;
    readonly "collapsible": MotionComponent<ClayCollapsibleProps>;
    readonly "dialogue-modal": MotionComponent<ClayDialogueModalProps>;
    readonly "hierarchy": MotionComponent<ClayHierarchyProps>;
    readonly "spinner": MotionComponent<ClaySpinnerProps>;
    readonly "progress": MotionComponent<ClayProgressProps>;
    readonly "toast-viewport": MotionComponent<ClayToastViewportProps>;
    readonly "color": MotionComponent<ClayColorProps>;
    readonly "icon": MotionComponent<ClayIconProps>;
    readonly "image": MotionComponent<ClayImageProps>;
    readonly "twemoji": MotionComponent<ClayTwemojiProps>;
    readonly "kbd": MotionComponent<ClayKbdProps>;
    readonly "skeleton": MotionComponent<ClaySkeletonProps>;
    readonly "slider": MotionComponent<ClaySliderProps>;
    readonly "radio": MotionComponent<ClayRadioProps>;
    readonly "radio-group": MotionComponent<ClayRadioGroupProps>;
    readonly "combobox": MotionComponent<ClayComboboxProps>;
    readonly "emoji-selector": MotionComponent<ClayEmojiSelectorProps>;
    readonly "pagination": MotionComponent<ClayPaginationProps>;
    readonly "tooltip": MotionComponent<ClayTooltipProps>;
    readonly "popover": MotionComponent<ClayPopoverProps>;
    readonly "dropdown-menu": MotionComponent<ClayDropdownMenuProps>;
    readonly "context-menu": MotionComponent<ClayContextMenuProps>;
    readonly "open-with": MotionComponent<ClayOpenWithProps>;
    readonly "collab-cursor": MotionComponent<ClayCollabCursorProps>;
    readonly "icon-toolbar": MotionComponent<ClayIconToolbarProps>;
    readonly "file-tree": MotionComponent<ClayFileTreeProps>;
    readonly "drag-board": MotionComponent<ClayDragBoardProps>;
    readonly "audio-playback": MotionComponent<ClayAudioPlaybackProps>;
    readonly "image-tile": MotionComponent<ClayImageTileProps>;
    readonly "command": MotionComponent<ClayCommandProps>;
  };
  export const motion: MotionByFamily & Record<string, MotionComponent<ClayAnyFamilyProps>>;
  export function MotionConfig(props: { readonly children?: ReactNode }): ReactNode;
  export function AnimatePresence(props: { readonly children?: ReactNode }): ReactNode;
}

declare module "react/motion" {
  export * from "motion/react";
}
